# All dilling-specific values needed to run the test: the dev2 endpoint, the
# store key, and the Grafana remote-write target + basic-auth creds. Kept in
# SOPS so none of it is published in this public repo and a fork (without the
# age key) can't decrypt it to run the test against our environment.
apiVersion: v1
kind: Secret
metadata:
    name: k6-secrets
stringData:
    K6_BASE_URL: ENC[AES256_GCM,data:5Aje3EkHDLEESglwwQPAdzeBFIrVARjv2UyXt4A4VUo+bKoI4LV9/V9ZmCG0tuavGW9ERuXEqdB08RkM5yC35Q==,iv:BzgrCWLQdyYDOIM+oCMt5vJkenY/GS/j/TwR4tG11Bg=,tag:Q3C81W7mNO6Ru6RFjsh7Fg==,type:str]
    K6_STORE_KEY: ENC[AES256_GCM,data:vGtkneLDoMqrrg==,iv:7nCpPN6amzYsgFCsJg7mNCHpULpyLqKqy/ibpyuzYF0=,tag:t51cVyDiAs0NJbGiBwVKcA==,type:str]
    K6_PROMETHEUS_RW_SERVER_URL: ENC[AES256_GCM,data:QsXMUPwVbRO3GYGk78uf8f66XjaTu4V3zZgBvsvmIBzPh2yIzO+bssnJ,iv:7UZnLkWF36CHTNZrQf7afXsG98sBD6UzbrRZRpvG2qg=,tag:S6/OcgjtbKmSeUKEmONWZg==,type:str]
    K6_PROMETHEUS_RW_USERNAME: ENC[AES256_GCM,data:DY2o9iRK,iv:6ZlVFylD/e3M+ad7RrxosuvpgokuJyVruh4gXP2hzX0=,tag:06bSeKUGClsUnkj8SBuVtg==,type:str]
    K6_PROMETHEUS_RW_PASSWORD: ENC[AES256_GCM,data:vpbR0NeGEhM=,iv:pXJuL/HLt9Kf6G47vMH5Pjp19Vk1QO+WtFI6mTq59SU=,tag:hDokW+dSgbQrm6CaUsyT4Q==,type:str]
sops:
    age:
        - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdEVRV015TCtYalc4Y2Rt
            QzNncTcweXNDY2l4REY2YnNxdVptS3pnZ2g4Cnh4U01wNkQzNUxyQmpvN3BBQjM4
            NWtFN1J4TDZVMXJjVTF2VXRkcmpLLzgKLS0tIEUwM3dPTHlrbWhma0pRUzBCUVly
            T2pvcG5WNFphcmhvTnR3NnZsWTNCVFEKkJNKjtRcg4Et77fHTBpmN6XRNQYYgSZc
            TqNLAHrQQL+rVlyWo2GV9JuY/XbZlde9STPygTP+mdNTYSJOLsBbgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T13:09:45Z"
    mac: ENC[AES256_GCM,data:2BVbiZk1dSSBljAZkJvpywJmWic5tD7Kiv572sA6+mHqeUz/4bhzHYTSiGUNDww6drcNLTtvb/BuwMnhTfEABVbAAeSiiWK9EZKt3RzmIUHYMqRPyyKhkp9YvrSN56oIGTtQzat6UMygMmso7vW8bNJ97pJrvnHBrwUo6UsLyec=,iv:Qv1Q04tLr9FRu0Mqn1PaLJzD7hljXilagUdtlvbupRQ=,tag:a18T8LKXoLtA+Lfe6shROw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
