# Fill in values before encrypting with: sops -e -i secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ticket0-ai-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:CBnfbXg7iPeMJP0vk4ttQX7uhf0ChY4W8sfR2/e0di6fRuHCX/2Cko+sT1JFZAtRSfbVtSmqb2cYHLWZaIB9yZ2F5wYKMJP/zh1v/uXUvvV46zS8mm2PSlEdahE0w/Wh5bKaPp/xayUAURNULppnOHlui7XntfQ51WcFunJEHz5LaEuB9sgsXFA1ZF/jaPfaDY13wIAO,iv:O1lB73QREI8vZ5KqWAd700W98fPtXWqK185CRAp86ls=,tag:jfLvESnJWE6kMqPkyPuHCg==,type:str]
  AI_KEY_ENCRYPTION_SECRET: ENC[AES256_GCM,data:Bg/krEwV3B89erCdkM8PgyVrYIQy09zJlGCfYIHIADosTDJpwEhPUB5pyYkK68n2o6PNu83FpKRafkTK3t4ZHA==,iv:DBsEJd8yodJUSPdTy30oyQb4rfq8jpJT8g3ZKh8lGIk=,tag:6LhX21E9wjmrHviPW/nfaA==,type:str]
  AI_SERVICE_API_KEY: ENC[AES256_GCM,data:cJa6NAU/WrDnyUXD9/VCp+Cq79MV8OqEMTY+JKt6D5A6IpoWM1wzgUhjvCw=,iv:e69mlXuJJIxOVFZznADnJDqgrJfVZkWMDM3By4F2Fds=,tag:DdZUu+f/O71UI0v5eDjdww==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMllSam9MM2c2U2k0LzE4
        NHBLNFdoVEM3TDNvY21DZ0FITjlVR0g1aERVCjhXTk1OYUxVVjl0NlFReDdNN0xy
        aWt0VVkzcGNjVGlrdGpDcmxpNzBiQWcKLS0tIHZZVkZ1WmJGbkFubTUwNEI1Tk5M
        U2V6TEJSWUFKNmozU20ydi9DYi8vbVEK/a4JOm3gxt1eqFLtUNcTz1LpxifmdWEb
        URBAV2FGIzl7r7IijzkiYVpDWugmA2qf1xm+G87qWKGQM56CYMKhQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T16:23:38Z"
  mac: ENC[AES256_GCM,data:L1GQD3qxtiSE5INjIzKPB04FUsJdpTP7NLWjZicBd5X7TSQJpWJw4JwsZpbhbqNWyxLWq5J6BTkWMj3EX0tYqPm7/s0F/GVC2kmQPRXHrRubE7bos4Yc2pealXwqLvqjYgn+SWQnpPB9tFYs/m3z0LPDzcV43W6YlH/fMNmb61I=,iv:FuWXS/WircVrm/MHoASCqBJXw/2nM661CJAGJn/HwbI=,tag:fcAuLpEo4Xq33petJcQAbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
