---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  chartRef:
    kind: OCIRepository
    name: seerr
  interval: 1h
  values:
    controllers:
      seerr:
        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: v3.1.0@sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9
            env:
              TZ: Europe/Copenhagen
              LOG_LEVEL: info
            probes:
              liveness: &probes
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 5055
    persistence:
      config:
        existingClaim: seerr
        globalMounts:
          - path: /app/config
      tmp:
        type: emptyDir
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "true"
          gatus.home-operations.com/name: Seerr
        hostnames:
          - "seerr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
