apiVersion: v1
kind: Secret
metadata:
  name: niles-secret
type: Opaque
stringData:
  NILES_SECRET_KEY: ENC[AES256_GCM,data:VcKKyj+/z3+N/hTF08POshnZyxlI37ryxNXoi28tmeiN1t1Aen+xZ8HZC9Q=,iv:aDZM7Sng3p+nkloLQs4vblrQwoioxfHQDKolDUKVT7Y=,tag:ggOa3l+8c9434dmCTF/UXg==,type:str]
  NILES_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:IUXOk1BTJRj73R41OgnNv2Ye5nE=,iv:i+fp8ifAoxJgojRkExsauxawv6Z7uLZuuIRRpCbnR58=,tag:7EETf/0Eh4+f8CA68RaRag==,type:str]
  NILES_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:SBcJ475i2HqGe6FwoNVJVjV49taqopA3HZjMTe7XiGmVFNEofNrwYw==,iv:fXgNCpFekrwyPC6Nl+yzxIXnK8xGOisHoyNuBnXkzIk=,tag:e5+xIgHskG2J6OQALaFP1w==,type:str]
  NILES_SESSION_SECRET: ENC[AES256_GCM,data:OcJ16K9Dl04n6KpgT6VtRgETlotxh8K1s//thVGn63+buhXxXdjVdb+R9qd3R37fFrXOwfNwL8nncSiu+0Wo7A==,iv:DpT759Welhwe5pBa+xYk2i9Y8DRIKSOzomBL+nHXDlc=,tag:PmJXfCtiyvr7jpTc7OdtxQ==,type:str]
  NILES_API_TOKEN: ENC[AES256_GCM,data:77ovjARHFeXJ7QOAspKnk3etFlqusoS5P9AOCEPb2k92UPX8TLxMEEvBG8o=,iv:Tv603CmrZPmGHQJVroadVShNc6zz6AP+wCC2BLfiBNA=,tag:p6MT6+rLKxk1CK/ZGaGhOQ==,type:str]
  NILES_MQTT_USERNAME: ENC[AES256_GCM,data:SSe51kc=,iv:1GJF7H5rCDsobi0ea27wasdCaXWL4415h6fPWu3G3AE=,tag:YDCsQGCp6sI1YnZNswBh5A==,type:str]
  NILES_MQTT_PASSWORD: ENC[AES256_GCM,data:XS3mbcA8yQvyYlnWjVZ9kroP2CGd3TvX,iv:GPLv25bZ+kLlD1MBBDNp63oEDx4iN36iV718niCS1CI=,tag:WAMghL8qG9n27cEjeE7tOw==,type:str]
  GROQ_API_KEY: ENC[AES256_GCM,data:Nq2plzSpZikvNj5a6OrZl3rUgiCf1nVtLDaw0Vux3p6A2MKeYXZmACGDP+T5UtPp4Xt5k5xrI8A=,iv:5s77MCPzj33I7RnRhqNNMicQvfUQh3Vd5+XxbZe+0lg=,tag:V1YJLbFUXWTSPveBQ5V+5A==,type:str]
  OPENAI_API_KEY: ""
  NILES_LINEAR_API_KEY: ""
  NILES_DATABASE_URL: ENC[AES256_GCM,data:KlK/a6lT24Zdq7F3yaf1hCvZDgFcAjJjhYg5h+i2SfkXq73aiUuzHALka8IB7C+zr8g57m8brgbluPGWVuI7D/i8eYrktahDoD3tL9NTnm7Bx7JjX+VBZsyXnoAHZcxtwIMk2tdmKdmwV8rcMFLSPdw78eeAFzDIgKPnvqfaLLLoV27adg==,iv:7eDTw+Aza4owFlt/4G+P4UU0kzZo/8kZiGLcNcgrayI=,tag:aFy7EoZNQFYOF1SKP0Nu1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZElPSVFrZG1kNDdFaEtX
        REwzZDRTc1NDSEFZVXBpTmNNcXZQSHB0RXhZCnZaeXVZRnBHZUU2Y2thQmJUcmFP
        SEorVWZoQWtZMy81ZjRHWm1pSEFZdmsKLS0tICtUcFFRNWVlVG15dnpYOFNPSzFX
        M01wWXFGSlJ4em1ubEFvNy9kQ1pLVEEKsxWEwKp1/iumgjjDoB1ZtT6thDb2NMsB
        sP/9IFFqhZzLUROhsLLj2Ekz1DS2wHKvViqpk1EBZ6Oe3zQF5pd7sw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T20:08:56Z"
  mac: ENC[AES256_GCM,data:B+eosOosrXQGvKyasri0hfE0nvk+i2qznfuykrGTQekCrBbOLNoURF/A5kyfvshHsPJllgsbb7O+KvLYYm1DMeihUEJKbV8g7ZQ28hyNTkyZh8xRVKYq3ARhCQPCs47spKab0HgZbnmM2dZXVA2N4/GeEMG/Ayx3fguqR9XGDNQ=,iv:9JbuzZ41dqGcetDfo3lvPo041fH5t97qNVpjH0Gph4k=,tag:ED4qsUAFd16qUPNdU9zpSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
