apiVersion: v1
kind: Secret
metadata:
  name: niles-secret
type: Opaque
stringData:
  NILES_SECRET_KEY: ENC[AES256_GCM,data:agPzGvK7NljE6hz/1WCUDEuILrPsCCItrFta+FlrzPobWqdymBz/fCl6eC4=,iv:KOvw8Vdw184MqwoI6mvF68gFllVHKw9ZZudIsCpJOKI=,tag:Q/i5AwqbQxTUTpy0NFN5bg==,type:str]
  NILES_SESSION_SECRET: ENC[AES256_GCM,data:bLT+7TDsUUjj75vGJ1dZojWdP+oo9lrJZi3oCQ8sXOn3KcPqPXzWd8F6ll3flE6weJUR2Ss+Xtc5MRLByhf95Q==,iv:7F3WmXPQqB7ccZqFfhT0ChfTMXnNDih/j6realkUkaQ=,tag:aMyR17BxUINXlAiRx9wwSw==,type:str]
  OPENAI_API_KEY: ""
  NILES_DATABASE_URL: ENC[AES256_GCM,data:G7A8NgMJP7i/sG3lQm90cLVrZUjfHvMDY2y8Ylp+TimuVLmSw6V+BjlOrR+o/bzkpWpD0taCOa9i/KSpUaNkJ3i1+NGnmbZRKc46TR3i9Gf52+ifY6ZBQjIXMgsXliXlCkqqoHAHl0t/sV43yHyZA9BmW68Sy/HVtsVq6eHsQOL8wchKNg==,iv:k7mFlUv5CsHQIABzd0TZUeFNgN4Uw8PmXl7cuv/XQJU=,tag:zwRPQoRP8agTnVo3FChDLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVWxVOFNqWVlPVEFtRHkw
        YTdBUkpTWjVpMXVjdkkzTTNEUDFCbVZpS0ZrClVib01CeWVSenRFSjhpeVd5dTBL
        V0U4R3RhOU9aV3E0KzdqUnNHYVJkd2sKLS0tIEdLUVFzVHJFNE1xQ3hMaVk2Rjdk
        U0lGZnoxR0VsWVQxVEZ4bDdmdm55bkUKhfh5OljBkmlLm+VuFTkmg004bXARFL/l
        26LlGWeEAhLHZ5Fb9FT6tAgIGbByfUf0Ua46Ucwkyf0lnYSQXMrvrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T21:02:55Z"
  mac: ENC[AES256_GCM,data:e+OHmyv4YOPZWypXq4epvY/N5hRYixrxI+2WcnIILcNKqkM17VrxtqIJV6xFCXZXf0K+YUMw6Sgj0RTHlKNnOql8LbY1XQVkXs4NK4loiEEUyFZLXZnfPlRQXezAjDo2x5X6jgrSsWSnntn89c/vIA4cUZXSspQlIcko0j8wWNk=,iv:/9Vt4eJS2LX4IhFmdLklB484dXDiPb4oUeZP8IHcDhU=,tag:a0gaT7OFPNlN90vx/IucSw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
