apiVersion: v1
kind: Secret
metadata:
  name: niles-secret
type: Opaque
stringData:
  NILES_MQTT_USERNAME: ENC[AES256_GCM,data:3tZBYXY=,iv:mWEo3KouDn5wQHSYrAySq1rR9BRXcIPaAruIxLP+0wE=,tag:/728PTSQZ7nWceIdbBwH5w==,type:str]
  NILES_MQTT_PASSWORD: ENC[AES256_GCM,data:DtK9dnIygYfoSq2hcT51KIS6uvYrEWFq,iv:KWDIo68IknAEerVnbtQ7N//+EQe0KF7C5p02YN8S0o8=,tag:5hTc5t1YMOet8KE4ZqPAjQ==,type:str]
  GROQ_API_KEY: ENC[AES256_GCM,data:DD1dnw+xuOPIfhLvz+wA8CD0Z9bfHqV2Whpn0whjNZcVidDpJ/AS01KkxbiK+7bWiLaMTEGKm74=,iv:PpfveUpignWF5HErC6XO3Vz7OH/3g/xMkJGZBByYP/0=,tag:+FRo/sZTDdjOG7vvc3GziA==,type:str]
  OPENAI_API_KEY: ""
  NILES_LINEAR_API_KEY: ""
  NILES_DATABASE_URL: ENC[AES256_GCM,data:+zI69swvoF9NFfFsCIcOsmKWhYDM7IbSgh6iDBYk2XIqZwPF45GSZk+5vwqNAOCqpdqWQ4LS6aVEd4G4xS85z5c/tH7BO9SM3C2SyBzLUSvbr6pLds7dZHWXdpy4woo8rtrdHtIRUR/D99HXD0d875IAZ0yyKPGg7EgkM3y+jU8v1C/C1w==,iv:pwWGj+biyPPstmFmlJ4uNhTlAZRNkzrZOk3kQQZD+4c=,tag:eMg0qaQ7fY4jy+DLvN8Ekw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUmg2YzAzbk9OblRzalVY
        R0o2RzVJYWszTlNxVGZLN3dCbktmNm83Z1NJCm0zMHlodFVYUlpvSkw1b29KcnR1
        UXhGNGtYQmdzc3JmVmZGRXJXNXJhdkkKLS0tIFd3YjFIWGFJVldiZFJSNVVKbk1i
        eFUwYk4rUVM5SVdOSzJaQlJuNWV3b1kKOyhzbIhFs69inIFxOL5jr2fhaXADMWCD
        pv1DSCRPk8E3x6OT0DCS81A1FDXWyG92zXAMTbsEnFBeJICBM332RA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T21:14:56Z"
  mac: ENC[AES256_GCM,data:p+HA4trJZv5ITKMxGii+eBo0z3KvYaGLtU6vhWIbvA5IIsJQ45A2jcwGf+knRfr+9YtaLG/HrvVKlFblJj9InPAhhCuSyUk72LWK9snIjyDgq8eP4iIlaP9EtkGuUWbrDb1gzznCXQfV8mIFpcHQMVYY1+GICFtGQLgKXCQAqN0=,iv:ol9nD6hKyO+uK5OGNB3Vbcog/WY1EpgoV0K1HA7lEqg=,tag:gGkI3/jZDXenwLJEgRBMyw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
