apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
type: Opaque
stringData:
  passwd: ENC[AES256_GCM,data:78c/jaiBWjZ88PtVpyvgqhfEAJ7BSU0hg/kuK612IlAtmAssRLIS4aqZqC4PqfHg9y2dqbWcunemOKpcj903q68RzNYoJrvPWwWJ4Ou7WYpqYO91qV3vFR3PQZm/I4uz1Xte6UqQ+8ZeVFbOx5RXsP1TPmQFX2G0tA2CtPNMeJ+MMlCyEnt5PlqopR3u+YGEx34JcZT8csVOqRDJ9tieLstSWUhXm5ndjSYXT/ta/rIoJ+SDpzKz7XiAIkcr356Ix3zuHb/ZpwgbIB8AdcnqA8pSJuAW3lWSJFyLIKXb6UuZ1ktZkUzF1slc3pMEVSSEuLmK/VnmL0X7409FbDY8mnqd918GY/Y32K4sWR/fa2dlC1+FNLyAK78iEwHAERxynfWIsSFjOqGYJkGqFDFJEUvNhzOGh92FPy9CJjBOg3z4MInbgKvu1nL4sRqn1OZd1kcwJ8OEZZ3CZddmGciRu+yJ9kNfnR1PqrGxfhtAMC5YH3FhB91PPozBi503TTHJ0Kr22GkwPodgQnHBAhZ2CI+3dROVF+NN/HnfSq+2Pj5H/kgtuCz8ir5R+YdgP4UuwhuQryUF9fFC4Ry6D7cPEqQPezvqycFbunLbStF/1O7D89mAzEAh+A8nQOf0I8GTIkucfyfa6pI9,iv:pdLE6ZQK4u29jjq3SZXi2c8okNWFF0HicyuI5xIwkQI=,tag:d4RnRQva4JAlyD16E3OQjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVDRuU0IyY0dweVlMN3cw
        ZTRvUUNkR25RNTFLOTM2L2NPN1E3Y1J4amgwCk5uTUZ2bU81WkxFTmsyNFlqS2FB
        WE5tUjFZZmFjUU9KaUFUN0VLWEFYL28KLS0tIFBpZkxBZlcyZHVGNGxHUGFaay9D
        djF2M1k0SUxNcG1XeWVkd3lhaENvWkEK7Lunzo7zRxml+0Cp7juOpiNCKJ+Ds1Va
        lGDPx7hDjZ1Ez20c6CoCKBpPld3LMeDUFeBIwIw98pb5rmGRd+ln+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T11:45:07Z"
  mac: ENC[AES256_GCM,data:ZfDlGCdT07fQndDUAcX6OgMHEqCirkOhPfKSkOXqybN9NEGogiEPt0VhGan51UVkJ2fnf6hXA1dKndWZ7KTXvKN1yb0blp4Pee6cy5x6uAjqGeu4KpENwRhqXApAwFSSXIMbQI8RIh8hpmn9fsXrHHXmcq3tjwkFwrlUR9zZ6WM=,iv:kCFbExviMR+cNCCju8RuthvL/5D+jaENFJPFKHrQ43U=,tag:j1Q7bEkwAdlYlCaVZSy+6w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
