apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
type: Opaque
stringData:
  passwd: ENC[AES256_GCM,data:rOxNF1lDdDggrGey8Y+KyptGIEi0qBqX8OdMdwefoJeLQAw/i0GMVgTXQxw63QF7qdFEZfsqtNo3HbBS6AJqRqWnEl6bErpuF97NN02ME5eXawgKyaUcpgCyNAsCZXES2an7EVEhegCHeXs7KNDabMND3YNFOMumXN5sfA3tXSNSZjYFn+K2SG0RMNPoD7iExpA636935RaXSoUgnUmpH8ILcDonKQxKu5LOCzCF9k/dz6DKfp77W6f3b1qrYP5nIp5HnpHVL1R/h7ubGqRih3Zk2KMDj+n1cIkvE6kIk7N9/f6/txk6YZf+FSdkO/XIfJC0,iv:R5G54SzIEaPDlwF0TMfa+qaqOkzNekS1sXfWQiAH2+A=,tag:SnpGp8t3O7fdi5Y/YIBJkw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOU96UDFiaVl0bXA4YTBK
        Sk1ZWnIrLzJJV0s5U1orQnlGaXEzTUhZaDE0CjlTd2NsWjdjVzNTNGR5dDBKWU95
        Tk5xanRLWjcyNURpUDl3SHFZenM5OUkKLS0tIHFFRk13c1hvcTIzVEZhU2sweFNE
        VTA2Z2U1Y2FmUmpGV0JXNFVtRHQ4VG8KIXimtD62euK4AD1ycEw5iszPNXqMo/kV
        r4MsJMX4+oG+SPQ3jg8mP2mPF1tGG6rPrcd2zYD7yn/wsguBvqpygQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T18:39:19Z"
  mac: ENC[AES256_GCM,data:qHGbou3qRliKNUiIlNuebR8DjCZpa4WuQb5WYs4SKCmR4F8y44POX9BYEesKHPx/MeEu+3ZZiLlmqNdPm4lsO3xbAMD0pEHo5hTw1QEB8OKbpKnYIbY5Z6lt1erD80/Hsr6+Kp/fXkua7kC1LHrzZEGNMKCHBMw3JVXT5YktGqc=,iv:AjRGSmYOTrwI/WGdbJRtylVj0rUFEA7TUycn33ePlwY=,tag:N8xXVp8df+icrFbreTRpew==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
