apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
type: Opaque
stringData:
  passwd: ENC[AES256_GCM,data:UDWXBTqs/sRXGKAnjcI8G7Y4zOpdFJVN4CYXtpohF+C7xs5QNKzCQGdJPaVUPAy5dtQR0gZ/YzbtlKNsi235iH+EdqOy7fkKEbcANo5sJvD95oWHQJhCZHUTmd2rKWECe0tdBXIdOcR3wh27IN4AZnACL1NLQYk=,iv:0iLORoTjCpjvI/cgfI42mh6ROWwn8lcAi5Gvs1CqhOY=,tag:L0phpy2Kd/jMJhfNCgVRuw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNGU3Umc3dHhOTDlOUXcv
        YmNQL1k4MmtWSWM5V1FKb3dxNklGcm42bEZzClJPUFRZZlhCQTA1UFFnSlJJZFYy
        SHZ1ZExMYzdCSzdET1VkMXptU3dsQjgKLS0tIFBJZDRKRnAxb1BrUk5ETFJRcWhV
        TXp6YzQxVS90YSt2Z2dINjdKa1NyZWsKXf9Q4U6ciDlDUVaFGbxqHQKGZE8CgNFQ
        QkgsggnRdqPyRxVc9qALhfnS+A27QGTfOyrrfur4b4DjpvAfoLFmMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T15:44:18Z"
  mac: ENC[AES256_GCM,data:HEFKEHEHMkY5wzE52aLTdHcWzi1ZWE07WF55IzvRFGmO3nm6ngw9qax9wHDyMsh0YxEo8cxVjWrn2WHZycf8ZnPYhmDnDH2Zj62PgNd4fKYGvxYyVRYQJvxrxaTiyOgutBkpjpP6j0JANgvQ3JAuwOUCQIpIgrrrMjnlAJq9xf0=,iv:4VTkZPaAY5vQMu7k9IJ6prdjjZkomwLvul7DzC6RaEw=,tag:qQS9VBUERN4bTq55DgB6Lg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
