apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:aYfI+0W9wbtiVa8YjgkbhWqLBtJeDA6EPcUXv1bG8VpmhJB9G1H69A==,iv:64m+FC8AJWMGAkf+5dzuP4saGk/sxBdIlDOu/5tmnR8=,tag:fDWuOwO8ZoFSmu+DyUtW3w==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTy93R2V1VCthellTQWJW
        NzFPMFEzRmJrZGxZZUl2ZU5DODdJKzd0TmlJCmNWRU5TdzlCU1hCQmx0ZHpIdTd5
        bWxQTVBsUEZSdFpKbjluTTFqT1pXaWcKLS0tIDdNMHE4alZDcUdnUEhxTDdTbTZM
        dksrbnZKOXQvVGNDN0RHaWlEZGpjd1EKhlohn5bKPaFHtB0ZAwOYGlCoG7fXWdY0
        ItRIvFDcfxKl4H8ZZqzZOgzPT6eJBTHUVW+gZB75MF++RV7E3tUP5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:06:35Z"
  mac: ENC[AES256_GCM,data:CXvVuOn4kM+3cT/FIkFu3KdfDWuM2ZzEVVpuwwxIQKzzgTSBlxB82Vm+1nhrvXe7teyIN9VKSuPMqex64+3oVRI+/IrJaOJCEbBU03PhGgSIYXZaNK0FpsubjYyFIJyxSb+DtLTEqd3U7SxhW7MkUCESHGE1ycoFxh/eiOtwtIQ=,iv:lKT7fHq4NYBRHFURZnhvL0CBVKC7EdD5+UjKqtOvoG8=,tag:Nkt6SCfiyWdIPXIDY6DFjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
