apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:RrXtWpvinLtkyd17qNUQsNvn1VP5yOJHrEt2qQ7zy/qLB3HMnC1dVQ==,iv:g8wXNDubUeU7ijw64QM4B1ae6suXKpL9bjDbvYdZ18k=,tag:ZOdBgO8XssROQV0tlxkcVw==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXluelpLb2V5RERuWmxa
        N0UxSG5HcTJXN1Fqc1JWL2pJUnd5amdscG04Ck5wQkRRU2NDTjkwS2N6d1lYMHdX
        amZpRVc3UE11RWJJeWxMdnVVR29Mb0UKLS0tIFZyTmlrazBYSCtrUjd3UnVjYUd6
        N29oWjBDS0xOWlpRZlo5Rm9SN2ZBeFkK+02LQINR36XCnHEGMtNePQ+tvwtPxO/2
        aST4OhfxKbn0CDcE8VGc1defScNlGA6SUNtho3MTe4SEXFb5DxZQEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:33:28Z"
  mac: ENC[AES256_GCM,data:VcSXkhRPDUfzDNEtgnmJiOLgGNUZ+ktw/U6tQyCWq7N/gl9bFlmDexuqfMgFy5JBZ7MEZcGhXWzCSYNmqlm6tAOpr7CxvOuSaWAm/81NACCbqEp97UCva6orInTPanzsRsAHN24DAO3GXGeFARba6w5a1rs+vTxN4s46Er9qSwI=,iv:+DTD5kBZ8dUOZkVmMYKFZv2kEhaEYNUIeSGYrykPASE=,tag:gFGB9ojOSwUvX9woa1AXYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
