apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:dfFIlkqZQQCVuCMl5w61pMGSQn1O+94EQsXngBsELRZs5b6SFR7k6Q==,iv:2oKn/u2zCx7yTnRC3umkbMfsszWSj4KzZzkdw8ih9Xg=,tag:b4rPjDKMFkmQjtQcWTWT9A==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOTc0SFB4Vit1SVhVTUZJ
        bFkwRU5GeDhObFJaZHNYeGp1dlJoakxvZVZ3ClBVTFhBSGhjS3NJNFRoM2tZVHFu
        bUl1VkFDdE1kbmtNQ1BsbUNDUTJQM2MKLS0tIHhsYXUvbUc5TTZGcjRKTDRCb2I5
        V0JWMTVIM0VSdExzUTZ1eHFCcFBmNXcKGmPkcG4q9KEll96OLLln0pv4x0XefRy/
        wuZGYRlBJRq2iqluMn7zxJVQ0MvJ9/3INnHBSsWNzQmgXenbD5JxKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T15:43:49Z"
  mac: ENC[AES256_GCM,data:6ol9Yz44+0lA8Wk9LSVNQHMu33pTSzSK3DwBHCvUjcQk7iWyL7NLBPpnSicKQWUZw64ZYhaT0pFLpHYCPcx9qZHjnXhzxKQez5x6c38R2WloR6wbeaq2JIX6GpFX7X7GrdSjM6/EIpAC1PDDrN0QfmXdqzqjpKMaqYr2auh64tA=,iv:5Wuy6474Moj5H6OJsdNAiVy6G2y/5AewRj07zrngf8g=,tag:1E+Ys4f1HEuGs5zezyohyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
