---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: archon
spec:
  dependsOn:
    - name: cloudnativepg-cluster
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/automation/archon/app
  postBuild:
    substitute:
      APP: archon
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: automation
  wait: false
