apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
stringData:
  UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:u94RZthbMt4=,iv:urWfelAsC4l9LEgMS872xxYEYcFjiitSzhAUi7vFhQk=,tag:2WocIfyfRnAREJU1O/qc9g==,type:str]
  UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:nbX84qm66SUt3CUnb5Vu,iv:qH4IMqVqmh2lECY1zLc+AhKlS+nFmFtXjtuqtDc44gc=,tag:Xqj42IqJgwl3fPvxeezMjg==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMME1CdjNzM2RSOEVSbnNr
        Wi91T3NUWnIwejJSTUhmcVFkN1dFVWRmK21RCjV0QWRDZ05LVCsyNU9HU0VVeFJy
        WkFCUExzSGhEdld2aUJXYVFYVXFWQ28KLS0tIDljWjFoOGNtcENoQmp2MnlSSyti
        VFczVFR3UDRERTBkRUU1QWJRYkpqQTgKPO59kOP5gyH/U9vgwHPv6638o5WGaH8y
        WdnVbzszxIB2EFIBtN9gn2SwVoHa3DlWM1eB/4GInsGZd8n7vj5oGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T21:15:16Z"
  mac: ENC[AES256_GCM,data:OcrW6ee0FkQKfz3DzPdWeMjvmlQvtLGzxVg8n+FtcM7Bj0vZsyWYbmbXAzUy+UWKKzCf5bHY98HLNgMsVMR0A1+it3qwridqOq0uUsqXEeWbmw8Agta5WlqtyQYxFE+YHTJJULDBxPef4h8Ou7r71OTDphr0Qye1TVDaGIsT6sU=,iv:m+apYXMcoh7F6H+QpX8s//osxUO8mu+cd1qmP3NzXt8=,tag:t0T0vKVDXcNmaS/F05pkYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
