apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:OyqqjO1VCM68DL4=,iv:6DIn6Iv5xLqRMVpPS+TJBgG2O6sTB0wSXp9ph2L1/rY=,tag:SuUxWVHer/nhCU+lRSA8tQ==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWWZiZ0pjOVlOd3FZODFM
        ZVZZdkxrbkE4TzNUb1JQZEhHYnd6aXJ6ZUh3CkxOYnFVc09ZVGZBQ0NTVGZYVk52
        RGttZy9MVTdHL3VpM2hBRzZoY0ROQ2cKLS0tIG1hZWJScHdUa1JqS1d3amdaT3Zr
        aG1HWm52TGtvamZKTFpnTFo0OFZ5eVEKSnlea4wKTUnY7xuRiNXnv78HkF2pIEjD
        Uzn3sqCmhH3Oz3tbmX9LIz7D+ta73JjXmddrNgRhktbqm3magNQLRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:33:28Z"
  mac: ENC[AES256_GCM,data:xMF4D+h9mQIkalY+5qMu7u5giqgG+iTPOuyCt7j+1ywL2OY4OTVSUnNyHZTqLc/z/yaHB3YB1hc8nlYI1pvylpfW94zUNePHczuoRR0tK/VuWF9yxo5lPL21VsAOLRslEwU4LYucTmupZTdFyVFj15CeWHf4X4TAsLNgFgOaRkc=,iv:FwtlWGpQkWcu3g9azzlm0QyfYFpJ+PohHEkuxC5q010=,tag:cYS9Ogw5AJDCpExSFx0caw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
