apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:2Vbt0wf6fddIh6w=,iv:9kX3GRnGQN2ZZ8M7uWwdI9xqh9noMlVH5ULBOr44ZBU=,tag:C3+WKB8PV1cwD50vosGnTw==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOU94RVZWT09aZzhNSDVQ
        ZzkyQmNNbWgvR2wyY0tJN3dtZDQ0TUFvZ0U0CjZtWFFSbkhObHloVXloN25VUVNr
        RFNPemJKemU0MDlCV0U2S2puSS9VSjgKLS0tIFpqMFErZlBHYTdKcTlmbldidzMw
        Nm1RS1dtQjNVZDRwdm9vSnZqd1prR3cKFiUCP5xRo2Fr0Bg8cZBTwOPQ5FZM7lhd
        v6WwkF3TXl9dBxIT12GeLb4OYoiIbENVeNY7V14N0MGLIz7Et9Zlbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T15:43:49Z"
  mac: ENC[AES256_GCM,data:ooE+m8mfgKEqFah3Yh2nzfsDyjg8OYIvLMImS5qwEyPv4VOWEk3IVy/PmazXxCavbnrW4NcMRt7buCUpYpHHXgCJ/+PVaHMNg6n6dQ/vFBQhOdGdl4fWo6Sf80C5WC4O0qbiyNHyBTOsIvCW2e9MIf8FE8gDrYUK5NdIcE39TMI=,iv:jHtoTLbyrz0YNPhGKFpgGvnUk26Eobk+WFAi8halp8Q=,tag:3Es4xJn015LJfxrFhMQlfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
