apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6pyUkjCeQzIf2J4=,iv:/bw0U4f/TjrboWN64G/Et0pwU5VdYKGpi1vRBCofR9I=,tag:DGZRVCbOiGBoaVZ1HHlNFw==,type:str]
  VOLSYNC_R2_BUCKET_URL: ENC[AES256_GCM,data:GefuO2PDyr/YnxAZiLwNjD/YjjlaajDo+qqc1bucvUuT9limqz9dI8G7dSX8dh4v/9EHrMGSbcoO/4Kn4Fxbwlu1Q1px550bF/i+/Qya7ocs,iv:ClkU+QJAZgr3HpQrtyQLOpsjIvUj6x+qqRuzd0Iluac=,tag:OLIam6Eldzwl8ZGasCEEjA==,type:str]
  VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:6Ykt7yWHzkQLkSMYhkzD2IOMd5jJA3WZQxPh5ICG5vZtCUHK/Pdq/W8dnmk2940IX9YJqUG1YaG0xGj2VpCZ0w==,iv:Wzeszm/TgvBiqhJaOLpyNXCXKBv+z+KXiTN03dhtmYk=,tag:0wrFMv16GhHfMDivVCoJvw==,type:str]
  VOLSYNC_R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:l5LyG3SqOLh65qtNSeoGpeW24r01o9dovuJWJOJ+HrI=,iv:nQRK6mXLRiZNPNC7hpladMJfU8OMCGpebRNqwQDc56M=,tag:BAgAcPFT0SJpEEq1QLvomQ==,type:str]
  VOLSYNC_R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MLwcoO6EnIBb2aOK9DI5UUNHRJOIHMvXrynfoWtnagcx2D+WJtBeQlCg5zpgCGN/YnQt9iSudvQoW7WSmeBE3A==,iv:MJ2knX8tuW62kZnNtglJiXYO9VN660zVpHe6iKXbrQE=,tag:anhmaqX+UHzCNtpwSdtHQQ==,type:str]
  R2_ENDPOINT_URL: ENC[AES256_GCM,data:UTfFIwHDjLf/WkBwkkTnf5861akx6I1yxQKhrmo+FMbgS+LrV0d2Kg1DCKyKeXJh/lAGY2UewZhDW5tk3hYVVmY=,iv:iUQgB24LBNYKcGbiGb2e6r9TPevQhl3s65mCefAMMgg=,tag:5jdo9UQQts5u//X37vtTNA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Wm4xbXNjNjJaNm1FSlRG
        RENyN1p5UUVxUmpyY1J5YnBFMi8xRDdXYURNCjg2MHRwZnJDMkswMDdJMEJmcHFz
        cnJxU1hiRFQrYmtUZC9Ka1RQZ0xwajQKLS0tICtFMStZYUpvVW9hZExqK2ZRdHdk
        cEU1YXVDeG45eFROeEw2bnpzRUxsYTgKaKiZEt1QUVg1reEEtoijfAWuY54WC05Z
        9LD44tyRH/2+heo4XHJIF6IIfTa1KGpqpSof1BniVS+7uNVGBo/gUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T17:04:05Z"
  mac: ENC[AES256_GCM,data:JZTR1lOymw0AFkd3EGCM0AuXWmx1MnBw/ult2wYuuI6MMHCOvF8HnvOk8DzU0qaGgdbpQJdrspj7Qvr8KTxRaJhJDJsHgwiBQTGf7b2dm4NF6Plg44JW4m0C/BItJA5LMai9PuE5gCzFKC2Nsts+JkKNbqQn1Odqqujdomf9k3Y=,iv:AHVXjPqKWXucyw1K6904X/h772mVrLj2K1FwduK27HM=,tag:nQDWL2lGcnw3WGouhP7VeA==,type:str]
  mac_only_encrypted: true
  version: 3.12.1
