apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:1WVus/6/9f+hoH19a6d7I8Ujc8//8ElGlp9cHbRcoUw=,iv:FslUfRx9De02rqP7d4aDpvBmPyzkR3tKhXSB+jJoufo=,tag:wVeFNGpK34TtcQJJksbHSA==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0enRYS0twdEtkMEZVVHRQ
        QnRCdDVBOUFmd2RKQnNvaFJGRG1vQmJaalFBCjJHVVcwbjI5d3VOQWE5RHI5T1R3
        Z3ROb3o4ZEdHU3Z5MzFseVQwS1ZsaWsKLS0tICt2cjczbkdieG9zdEN3TldOcWR1
        aEx0S0g1MzhwQzlWSi93SEFWM3p3WmMKPV3IlYMGWnDBTaaY3SMiIO4jN8Pdu8+d
        no1uWGUVmrcwfN0BBa+Y2jsp2KUH36CUwLDrlNz37ZCONiqo2NJy1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T15:43:49Z"
  mac: ENC[AES256_GCM,data:0dZZcAUREfEsPbaWZv+XbXzhLnVWUKwzZj8VX+WVRErolFCxGlm3u6o9Epv+rsWdJ68GRpbVUK4ojdmGP58PGndQRhTOyL5oSDVqLNsQ7W+gNVtknBf6ksBF+FEtew6LGQKIGexGZE0u22LYWhfFqZC0rUkdG4wMgSleW0Yqteo=,iv:rPVsB49MFj55uGZKxWjtWkQLIsvoED+iBEKHz8PX7J0=,tag:D+FDpNWolAQ3ib1M5I+3GQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
