apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:L2CiEMekHYJTetAiMosz2vGWfA02MJYBUDUqMy9gq3U=,iv:V9W71qEsQ7/aLjGCVyQUyGnfdqhVcyEByFptnHpUKdQ=,tag:L+fiikZTqwkWuKp/E6+ANg==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReFJxT0g3cWFZcyt4ck1z
        SXZaSUgvT04rTG1KOEpma2owYlIybkZMZmdZCktCYzVaREw1VEQ5T3pCY0pCTU1l
        dUF0MFJEa1NzZFpnUWpaa0gxTTRKV2cKLS0tIExCeUpZbHFzN1pkRGxiNGppRTkr
        bzd1bVZFTlJTTmFZeXppek5UTTY5NE0KMbvvPiKPORT9vInL0G8TX6VIzA8HZyRS
        jMgharUmUH+OJdRPe6SJ89E8X+LfMB9tOO1J62VrDNoQyA0XmRfKnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:07:12Z"
  mac: ENC[AES256_GCM,data:enX8ef0P1whrlh11g+RBDdIpEiXXRBqFfWPEMo/5UTnjGt1IsKnXxV7hhXb9+GwsQYikUyfT0T0XpSGp72ajvY3X8PUE6emZCxlnnY/x+phzFqrYLN9PamOAzXq+A3U7cYdMikXfSmh+tgppXzCSrMNhuVjWMxVvrHYddaBqBFQ=,iv:fZ0t7YJQQq8BYhWeiE017Vc+7wTLoSxhhhNhz6CvWfY=,tag:OyKmMKgRh8ebCdmzcegfPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
