apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:9G0paTWJZeGHh0clNQsI2cV/FYpoVfThndZgtyPUP/U=,iv:y675maaTx+t0QJ0jSIDZZX6e/auFHwjuyfxdpVUwrIk=,tag:ZYtarxO39ZrpF7hrl75/eA==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod3FDMUswb2pkeFVJYVkr
        VlVhWlpZMkwweWt1Y0g0cWRFSCtzYUk5TUg4CnA1aWl6YVgrSHNPaG95SFdVNnha
        cFhxQWg3MlRXUGwxb25Lano3UFJsaDgKLS0tIEZRV201WmFKbk5UOWhLQ2lJMEJv
        VXRQWW5zWjF6OHhRYVFqYkdRcjl3TTQK5ZEbZUyDegI8sU7nLvRLKmr3TfSbD2Js
        j6gjj38BlDgJ/5+oQAtiI02W4h6rAFNY2mHHlsRymbhmawW2scao+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:33:28Z"
  mac: ENC[AES256_GCM,data:rhfhfZ+PxHJtaWSFzIhoFM7a1MKvXkW4ViOAS1s/FXFmvdg3l+GomN0crWjU1V/rkn6yIySI+zoDbymSN0uXF7FbHiNcQprzzV7rdBmGAQHmoSieV20q9km36CNrhW8JfTzGK6NP32QcDsSAu25Oam6QbpV/++e7of0nwu/LExE=,iv:smyf05SC7+kKzdQeG+WhFzBlFl2OPXoNbYPm6cRINgs=,tag:UpwuEZNRFdmp7Vcxg2o9pA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
