---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnativepg
spec:
  chartRef:
    kind: OCIRepository
    name: cloudnativepg
  interval: 1h
  values:
    crds:
      create: true
