apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Jl2Jsib/gW2AqzgBOgaYn1xI3ovpa3zGzaco1GToXsp6kTlsUYgP5eTPIrk=,iv:DzMysr+Eu9C0tXZcU+E7R73OgUtarXwnQrQ6klrs/7g=,tag:kgt+mZ2zvAzSLcPpEcC/lA==,type:str]
  WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:GdSNsWNZIkua5d+t8xNStRkJtgzZddRc5IoToO9atheKl+Z+kcFcSS3mh7I=,iv:h1+eyV01yVPfI6GRfqBUCe3c61qFmccsUtAdKfW+WzM=,tag:zZCNCofTSc1xHD6V3i/vBQ==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:qBJHXSUsOo/d8eGgvA4t,iv:bPUOrjdHz5IcWfSkT9jUkao1S5RzoGtH54IhA4npt8Y=,tag:y9taDaj0hYqk47c40/SnlQ==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNXJGZmNheVJHeHVaNnBw
        MkkyRUJGeHFFUC9ZRENWZTFoNnRNaHkrc1VvCkg5a0lHRUd5TWZIS3BlWUlzNTIr
        VVk3Qm42UFJLT3FSNE12VmpJRFYvWkUKLS0tIC9kYzFyT2lNYlVLMVk1YjBCNmhq
        WWtUZTdKWEpFU3FaQitPcCsrRG9GSUUKexWgbnaL7/7P8s751qkwD0R3u99v33rp
        WpyLlr/U8jm46Jt3R+7HG/T377ficd+/aQLCDnE6T4NoUuudMLOI4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T21:52:21Z"
  mac: ENC[AES256_GCM,data:3LopaV70aueKY+q8dvG+iueVAmlfAQfjZDd4yvfedoP7oW0VRzXLLh3NApj/bDGJedL2I/5iFzDq8/16Lt5AXYHtnvz4HjbtQTGkvdEEg7yak4WeUfnvi4BPCH3oELiLa93RnPqp7TjGTPzFMG8hCNi7NPg2k6Ny1rYju53zH+g=,iv:m95O9+Tsm0/VQsQbl6w77bAvP2ZFLbN3tO8f0wSk1+Q=,tag:9VTURd8WoBYgXcSa1B18Mg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
