apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:PH039x3fEn0yTGA1KGdXedMXBUuAJpCruEHWwmJunaQ=,iv:FFd3qFPxpsInMDO3b/56xvf0pfRDcBL4YBmTAMpN20E=,tag:3oFhHl0guGZfeKDhwB/HfQ==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:+OZ2tFZTgaS615MHrHC/nJDMQ4uuq1MLISnoHs9CWlw=,iv:HOPHPY50F++QtunEA4wdH7Uvb5xpa/bA6uH7QM8mh+I=,tag:FzgK5py1RKAVQoiKuGo1mQ==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSVlwa2RlNWFpNDFNQmEr
        WitXd1drNnRrbDkyYnRVbjlPM05kNnhpUzBjCmxOaWRET21uT1JVVWdtbStZdjBv
        RHBGTnk0NmEwa21ITmNueURnZ2VoMFkKLS0tIG9hRWZUL0VnRFdOb0QxMEFSRlp5
        R3NMcUhIZUQxOVZPMVdiUmRtdE5sbUEKhufxEuFE57I1CAzuPLEDtJaChbLPJ6gD
        VKsF9wEUNxqKo8yPgoFpDJsLOhwiE2r4un7gm4sxHYmzUU5oLiZ/oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T22:16:29Z"
  mac: ENC[AES256_GCM,data:yVUexVUlRx6yILdV6luXSSRMXZvrP0PJ1XvvRTMyMDkBzCxvHA9OR5JJPizrQNOrydSnXfPPn9zcJ8rqwLlOq3rlRPYuCyA1EkEVWNtbuDicUGm/XnSl3C/mUwer81TsjvzR18mHMxf36+YT4L6BN5+OTSbBoDwO87EBTtbLwQU=,iv:Bt6XJXN4GPQ+h+Jo2CrjN4HVBH49BGETO/tFlfV4qlc=,tag:JyyAbJfdzVTRszbNsX7CmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
