apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:C/yYu66MmmDezcio7DgTn8UB+v4n78EkbcvFb4B/u/s=,iv:aLEq/aw/4PbjqCIgLBt5gV2jUxIFabvpF3XwvSxE58A=,tag:68TvuMZmLRwU0j3Ege/s8g==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q0wzZWVDVkhvNGpBdFNo
        Z2pFUERsanova0RRU2JaY0dMK0ZUR2t2Y3lFCjkvNGZEa2xmTldNdExYd2ZxZmto
        T0h5NWEzaGdpTHNISDRTWGpoMUh3Y28KLS0tIDdzZFN0N01Dalh5ektrWm9oZFNQ
        czZRYUwweFZXQWx1aWNCeVRCbEhwc3cKHNgydUB0/lJfNDwDjszhFUDdgw8rVVzs
        e94onWoVs8FtXADTvxAl3mSXmzNi7Gu2/1KVML1GgKEz1cDlp0uviQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T22:16:15Z"
  mac: ENC[AES256_GCM,data:SruKAmDEVfe8UefNDt467xn9Lp2plrmxZ3ahaSnjUIsyw1uW3pAHF1x/SidXdkItfB5Yo7bAmjdS6lePU9dNxcUOQ6dVylQWCAwU7rPMNyJAtG44Y0wSBavLl/jzgIySjIWRkU4OIzt0If4COD5apywRavh7s2yL6Ah+fSVNwB4=,iv:VbXRCdhe8p737t0rZ2p+gFHNXeQiCRDhACZIqlykkSU=,tag:/F8QQ1JpCK8Muc1B47SJDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
