apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
type: Opaque
stringData:
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:vN8RiYF+pmltVZNq/Uuz069fCA5XfuxX,iv:moVQ/knVweBc1UadHQaMfGB7pL0nP3AVhYrqYHpVRXg=,tag:rTbtMaG0LM8q0hXVbMGZ4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYUNkN2lCaWUzeXlCS0tp
        RDJnVWo2MzdhM2ZzcGpFZnlpTGVPazlBdlgwCk0wZkE2Ymk0ZzhCZGorOEhTM000
        eHprVDBJT29TVGZ6NEswRFNhQ3h3QVUKLS0tIDMwUDRockJnTTh2ek9haWk3KzQ0
        YzR6SkJBaWFidmExOFZhbzRnWWdlRm8KlHqMmDqYCzayX8fMtfZeG+7ZhJiIhMa1
        muTJfnEozxdxqpVwkEtFN3XUHitTMN2bgroUhEO8ujvYdXmsZ5Iwzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T18:39:19Z"
  mac: ENC[AES256_GCM,data:WpW3BnevthxYiUinZDfR3R14Z4FU13gwAzPiYXxPWTIf9ynQcDndeUsafvhAPkqxvJtPJmmkIVeTN7b3XlXPHrdI14jLZFBOW+RhbmqYbZCZj4MGH3mtFXZh52V/APfPxfltW1LXrMat0m3mmGCX0Tj4COPACrhTPE5Y/wctZPA=,iv:NrLW4GmAZF/RLSGEkFrywKPqInuH93nD9pAO4jKdyEE=,tag:wtJko6HBqnCeeQxi+slzyQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
