# Fill in the values, then encrypt with: sops -e -i secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:jZ0IEqnmUmFDTNwuwLIi44nV7LwzyhNJTyhrKgxWJH5zNqxtRJywSxtWfQ4InFo/hEKaatFiEG4qElK3ezO4APERhhsJeslAgj+DhFK1v6NXD1tj6g1otO+Vj4E+BccrAlEOcA==,iv:7hbVwSoO3cf/YLOXQsrXpJjDCae4Ficqifj73c7dNC8=,tag:dILh0XxN/SrFPFGE2+W/Mg==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:JbKQ4Mir5V1zz378GF/YQvzAJg8hBHC0Cu2Fx4+vVEWCQfJpJC3SSdqnqwisaKbeUgg1KvnY76uaHt05okSYuw==,iv:IrY6lbPod6m93ld/Snj4FNOqITl73NqP4HIykQ66lNk=,tag:lHKB2K6n2Q3YJ49e8a5mKA==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdDRWZlM5TDN2TXFjMnhr
        WitoaEp4dHgzV3ZRZTVrVEFSTHRmVk5EVmxNCmdhbHZpalplQm1CMjFpdTRZbFhV
        WSsrM3Q5RHRGc1pHSHBBaVdpaWQySTQKLS0tIG9XcXM3RERuRitEajR5eFdIUWhY
        TkgrRVpoSXFVR0RPMWR6cDIwSkFzcWcKqvFewQmi42VxdS9h4HkKDJAo+RmZRQFR
        52KfsGvGdm+yrOJllo3s+L6hJvG+TgfIotTDN9DhRwHf/OFytNe+Vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T19:07:47Z"
  mac: ENC[AES256_GCM,data:zVF5RAuvK8b6kksT/BxJ+7wzo3XwnTeN169qre+hJo5WoF3suWP+aRaol2IQ4vjH3LHYhZFRZYuOR2G8+rsAil1JarbHJ6L2PsfUJoYUaCgJhaPTzFb3fVMWYQPKn5XU46EdmixBfIjSLYMUGsyKVs0GPs4sIGycGlserebd5r0=,iv:kwNuatGjCgQ/d7ay915RF7BZyL48tvNJw9IlvwUXJYs=,tag:6yRJEoR1rnCj2JnInor/lQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
