# All dilling-specific values needed to run the test: the dev2 endpoint, the
# store key, and the Grafana remote-write target + basic-auth creds. Kept in
# SOPS so none of it is published in this public repo and a fork (without the
# age key) can't decrypt it to run the test against our environment.
apiVersion: v1
kind: Secret
metadata:
    name: k6-secrets
stringData:
    K6_BASE_URL: ENC[AES256_GCM,data:mjWdMsTmAqo9mtuMxsUQxjJpINR7pjEVSvB5JJ2d0cfBGYyGOjA9+DMilbxIiXDMKkopxW49QyxwOjZOEKo8ug==,iv:20630ITxXdCBELdQtCDaftIOlK4xQd8HyY+yoBFNUSY=,tag:hWmhlgOC5W1nJaZbCbQSuA==,type:str]
    K6_STORE_KEY: ENC[AES256_GCM,data:aFtk6F+6fSxdig==,iv:EaDimBG1Sj7Gq3Jui90JU5DDHkQiJjQrYx8TWXFBIME=,tag:lfWCZ5d5Mocab7gBqr/n/w==,type:str]
    K6_PROMETHEUS_RW_SERVER_URL: ENC[AES256_GCM,data:Z5Yzhy+a7+/JCHqWwSitDyWingk0qR+3scokiYKsf1oVxHAdf705Zy17,iv:aDfejsolHLgqHufWLOV4DREvRXQaZ2AGvrKIrlC61/M=,tag:M0ymS2PFmjfyQkiQOO6wvg==,type:str]
    K6_PROMETHEUS_RW_USERNAME: ENC[AES256_GCM,data:apxaPXNG,iv:FqjDFVMfw1Wq3jgIT/r7T8GJd7A3Qv9eQ674vxLaZtQ=,tag:6Mg8jO5K0yyH6/YKRS52kg==,type:str]
    K6_PROMETHEUS_RW_PASSWORD: ENC[AES256_GCM,data:Bk2RQ0NL/CY=,iv:W9sWcic8Rn/lgDCX0bcxRItfboSs+LgHJ4LdtH/Yjvo=,tag:/DZfDVL9w9XjfhZUc3rJPA==,type:str]
sops:
    age:
        - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RDUwU1hSNGFidjhHM29B
            RkhKNllWUFFFbFJLeXYzN2E0OENCRHlnbUJFCldEL1VEOENKT3kwK1pBYXAveUVt
            ZHl2MlNpMzA0UkpqTWdadVFpdEJwRkkKLS0tIFlmRVhFMHlxaTdGa0t0TDBKNGJO
            OWdoSkJVMzhhZUVGY0doN2pJenRoVHcKn0iof424OsZ89gVLxYp5f7kS+Us0b54v
            5EToJrBL8Yxh3UV80A6TZ1Bew8bUywygzecHkmw1r/2jjFmhP/nXtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T13:09:45Z"
    mac: ENC[AES256_GCM,data:xAXdlV+XMVIjwHlOESC+i9FyYYhvjZJ8cSuQ7VYNiWmcthhXQ34xQpqUu4DGO6uh4wm2UFP/RU9vcPbE1y3Eq6YPznFyaSnaL/ROE5u+OvpDTjfhVoY195JLgg5cI1reK9YcBkEhqZkd3kAxTtENN8or+O6VomxdDxMF0UI9V5Q=,iv:/InHC6wdlgNxIKEBfBSS6ex9m93/sdZU1m1oHsutch8=,tag:7XUnMBl0LasTCfqRwpIGdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
