# Same dilling Prometheus remote-write creds as the inventory test. Each test
# dir is self-contained so it can be activated/pruned independently.
# Encrypted with SOPS (age); decrypted in-cluster by kustomize-controller.
apiVersion: v1
kind: Secret
metadata:
    name: k6-prometheus-rw
stringData:
    K6_PROMETHEUS_RW_USERNAME: ENC[AES256_GCM,data:F2UhBwdw,iv:wUSgKnhUE5SpKpVcipMdLZZz6t4p8HuAwkM/ChGcuQA=,tag:QqGLc+BVqoDdJ3OeOz1Tgg==,type:str]
    K6_PROMETHEUS_RW_PASSWORD: ENC[AES256_GCM,data:h4l48gyC9ZI=,iv:Z8ngpL9hS7ILgWRA/GOEyqR0KisLIa5mY2ID/cIPcgk=,tag:la+KeoRt/9aPt94ppZ43cQ==,type:str]
sops:
    age:
        - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRng5RVBiVit3MjZTZXB0
            cDB2MVJtZVRQdFI1bnZyQ2EzMXh5QlIwekZFClJlVDRDRy81RkNZZUcwdjN1UXZn
            eGFEcmhOM3F4R3pUNFgxOUpoS09aSkEKLS0tIGllOEFMSVpCU1d2VWt5OWV3Ynl5
            V09NWk9sc3ZTeVVERFdORGFOcFJpQmcKLngVdn7I6RG8RKPMYLJ6yfoQP0s+kUum
            ZCXG2+uH/jUgIiZn/Lq0xNXuu/luGYLvrRXlLx87aE6NNfUnsH9iZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T08:40:03Z"
    mac: ENC[AES256_GCM,data:fpJUk2OWKwJTdBc2qxvhy7gB1fXpfes4pvcv8gy547YUsZgFNUjh+hoe7oOFYWZ/vx3kE1IdJfTPad0xMUdIETRAmBJQL4V0imRVDLrjTTIQhB6LhC63qTECilh88tUk0gEo2GQijGkVxr4zlWLyz6Ml2VVPA9/6Mi40sD/elYs=,iv:wZ4I/zkh+9MLGxB+2xPE7HJ7FOP34zlOqQjl1oxjUcs=,tag:PHet984Auu2iYsp9yn+kuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
