apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:ayKXi+GT9Dp3DJVl6gOfOi0yvV6FHvHsP4ePjkXATu2Wr8qnJ4PpDJ4rYXbSuOzgPn77B2UNDaaG256x0BjXeg==,iv:iJzeBZHyfSLGKQ4EhbaD+qDjEoqFdClm3sN8wClx2zg=,tag:wB0swgyYmuRJY9QZiZugBg==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:gRMzZm2hr8BNc1o3nfzFB8GnZ7NK5pBfPDYjErftRk/JkqDY3QXvSaHy5TYs8/if,iv:P5U49MKD8JT2aW/M/d1YY54lOE4UrxZA2jWs0LLm4mg=,tag:nkkPLYB4lHm/5yrx6bfbNg==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR09iRW1GQ1Z2REs5TXRp
        QUkwMDJVeGpSVUwzUDVKL2doYjRRQUMzd2o0Cnc5VC9NNENWRlJIR2xtd1RIMGk4
        T3h4U2hMSGlVYkphTFpOVU0vNWlXYVEKLS0tIEU4NTg5R0g5cWo1M250NENqVWps
        UVBuT2tTYnlpZjdmc1pQanNXVmJGRlEKICN01ASH/SOu71T41CrWdBGpeLYgrG2K
        xY8JAoVmK8Qw9B+N/2Pl5mENfUkDKLaBJNLDtsIvs5Rp12pmiwxNWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T17:57:43Z"
  mac: ENC[AES256_GCM,data:rWGmQWwOTRcz+oJEQiLjuelVt5KyJHg+61OLXgs2XSWNuJwO+kS2ny2PqZaVKbknCGvimHRsmee3VzPYXfc3SWV468Jza4JHeFa7XAFumDPNgL3DrYUvazID8V6JDPfynvWUSyzEuDDsk2RPsUnQOdsL1WY+99qcZUBqHUC4qF0=,iv:aB3Ji+TB9A9MpD0ItjRQNAFhBautiXLdCa39qWOVdQ8=,tag:n2qnHAcDBFCEHdFZ3CbNLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
