# IMPORTANT: This file needs to be encrypted with SOPS before committing.
# Run from WSL2: sops --encrypt --in-place kubernetes/apps/network/unifi-mcp-server/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: unifi-mcp-server-secret
stringData:
  #ENC[AES256_GCM,data:MvylmdUvx7aFgUttQiBzbA4jvrft1Wsggv8xnyUuuZiDwombMbcjTLdghFuz7jhf7yp8Zz5TBvLYiEe+5zTIfkoykuimBWRreZ7yJ9hxnIG2sq1qhWJqGAnDmA==,iv:j14+Pi5pD8GoQpakGv1rrntat0smNxVEtel9+igV7J8=,tag:1lGZDPC2ydclypop8H1jSA==,type:comment]
  #ENC[AES256_GCM,data:rxssmCPNU53nc0UVZoriSzmxFMSXJckeiIJoZZE7Dnz/fiYZ8semsqQn1Usl+IPfypVD1TbTWEIJo9P/7UDTwFN91tlYWr4E7SM=,iv:AaIH6z7z+3I1ea+V/zOtYCyKAcUSNJ8jXFELMSnPe44=,tag:bQ5ljS+4vKzUeC3X3qsn6Q==,type:comment]
  #ENC[AES256_GCM,data:59EA6esNT5kFFZ8Vl7IsmJnV/Q7r6hTUhPv0T5fF8lKaEdtXLa4QP9UHCk/GjJkXGG+VJ8jyv9UZaV8Ae5iOiZPde2e+Gks3mMg5XQ==,iv:0GnPQBSYXhUdZXlFZkp0OaqrtpaR7RRrnF+a96fAy8o=,tag:38aLO7tXhJEyAIFKWL5vwg==,type:comment]
  UNIFI_API_KEY: ENC[AES256_GCM,data:pIF9nhe+EBW5NWR4dt65mL73V/icNjPG4RqnHOm5NK0=,iv:AfJxpGjam6K+g7t9kOk9sToswSJvYrPrIGvIvOb6Ues=,tag:BSivwfLQuo9NSnzreRvo9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NHBZRkhuTjd0UnhzYTRE
        d1l3eitFTHdjdGZwUHJwZzNNbjdteTZnelhnCkpmRkZHWUY5bnlSUGFyS2ZQR1dN
        S1BXZnRJNXRNOFI2MXpsRFczNWN4eVUKLS0tIC83b2pRY2wwcXUxd0s5NnFpVS9x
        OVJ2M1hwWFZodUF5TldiSENOZUozTUkKlx9srjOp0VK1dvK1ELr54rF/aBE4lyj6
        AHBtceOmZAnU8lfCuC7Vhu0pUXqu977ZKMObHo3dYKJq9zyBgeNPhw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T17:41:54Z"
  mac: ENC[AES256_GCM,data:kIbEwxibZAepT4i1Vsq66VxvJvQs87AVomuLNk5fXRADX1DGQ6emS94iIw0clKULjWhu9b++1oI29xKfmFUL4IEMJpWAIPxC9huIzbJAOSlV3mPL2p0QgmEoiMQolXQhHpdD9TL41zSs4ILE/lqhzkkg++kd3dF2ul1H8lKyT5o=,iv:2CAsmqqgbe7Z71d3NPzvpXEoj9Ls8H7DxpAuU1HIa/k=,tag:EeF2DuK+eKWrsFJ7l5HmBg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
