# IMPORTANT: This file needs to be encrypted with SOPS before committing.
# Run from WSL2: sops --encrypt --in-place kubernetes/apps/automation/home-ops-agent/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: home-ops-agent-secret
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:WaIF7v03V9L0iYShQH8vUVtpeL1sXDZvAbpFj0kV9Q664v++axcdG9a9VkXC/MWg00H01MnQuHcr7s8WIeSBLCEgjgg/TRHvd1xOdeI5cvKzZhTuZzhvjVDJaRJe,iv:/l+sleIxgvaRA6ND2jNTsLFj/F/vFaz55ftY+2IzxXY=,tag:L3cgdRNyE2WjDMGgdQFU7Q==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:7IWwq7+bky6WTcV67xrm8sGVk5MEcItouc5eLJRItoAjRHQbn+FW4O/dLRAmi1LOtsvQyLC2J5gki/hhq+40y0PxN3dQGGpzN4+JpOEK5ywbzy+AXCpoMK6UHV8f6PhLj9zrxAGzjCua1bWhIjXMt3z7mlHVoiJQE8YWk4fEiz7tXGgGG+oLCLp/ew==,iv:UjmfLYtJmmpJV+xNEWqW16+gsnaGRDhd9Eru1RD2oUU=,tag:x1vOcSWnrS4EZgVdSqBKSQ==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:cQv2YORiXRoUEcy+wf+wlzDStG2n/w+fjaPkwlpE+SufnVhKCcDpkLWgdEQ=,iv:TS9x+h3/vaGhPAD2P6tUHI3lCGwzmC93/sGW+9SXgjw=,tag:2olUvFD+Kaox4nct0QHCBQ==,type:str]
  #ENC[AES256_GCM,data:GZ663H81+dOlyWYumopMsTwSTPbpd1uiMHgmZGAxYphYcNpIubWGbbhpY9XC8CYBq5kwV0OrjElwju+nbTS69B7+y2Bh,iv:iMi2EQjGTNXXukMaSnVSD/jqRFVNMzVwF948IQqOLUs=,tag:hcQHuRuy9ObnM2NL+QLg8w==,type:comment]
  #ENC[AES256_GCM,data:lL/lFZxH2lGvSJ91A7DlputvHwBKKFQ/rwb+aQjV3GONMvgCvK1xnj7oD6AljOONcMaroJ4dDaBqVZl3tGLoZV91Ymkv04xDGw==,iv:KXMYFch12enrC7IsoMP7hStozdEgpubhjQMwYU4+mKc=,tag:2u+FdGBDMM42a7mEiIivYg==,type:comment]
  ANTHROPIC_CLIENT_ID: ""
  ANTHROPIC_CLIENT_SECRET: ""
  #ENC[AES256_GCM,data:W2d36y/cXpqpvjn+loHa86ZNdUqGjwQruLpYqrt5DOnHaHatwX6mrYMF31g0WJACUHlTF28GInBsTfphog==,iv:oNgryKAHiP188k75/RChMmylNLgbEIbu1awvbp1Q40I=,tag:X7JCNDAOuY0k4fnd3CsoHQ==,type:comment]
  #ENC[AES256_GCM,data:64J5zSGnv40pFrA+6IDzaBPHrHl12Q==,iv:WJaNZKwU4i3kFOrv4d47ack0jAKpbpwVGWx635KFqCM=,tag:ZIepBcMN1PMJF+91DMPmmA==,type:comment]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYVJwR3ZqaTN0QmhieHNl
        aVBkQTNYL3hZODhYQlpIcGRPbWc0RE1PVFRRCnQ3LzZ5SlpoSWRULzZHUnc1YWpm
        cWtSNVpJQ001UWs5OW1rTWxvYWV5c1EKLS0tIHBRV21uUUZ4Z1VWelcxU29BVThE
        d0JLdmN5SnlwdjkwS2xlWlZUeEpoN2MKh2mh0NtFOSWgoGfG95d421kmcLq/AR5Z
        DoskocbLiNTwg0zrrEurhG9gXBMaeRUIjsOp1vlehhCLs0ti+mpKVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T18:31:54Z"
  mac: ENC[AES256_GCM,data:wRFX3Inbo//GgMIfKQ7+fzja6RtyyxyiKQlTptls7/oyfCxfJaWAxczKW7ree12xtb8aFCYtBmrYqnMNLFAqVOZUhegDTe40z9/zBAxoSm1K515pcs+ZxkBSX2OiI3FoVKC/LOoX0OdfP5ZyqKn5glivsKoatfeBW0RIdFnDJsg=,iv:LEm+t5/9LiFEgtQeqiXysw34TXMBPmVRaWAmE5aqjFo=,tag:pvvi1jQUJWv5Lmz9FzBUZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
