# IMPORTANT: This file needs to be encrypted with SOPS before committing.
# Run from WSL2: sops --encrypt --in-place kubernetes/apps/automation/home-ops-agent/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: home-ops-agent-secret
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:4XvD5PEkkLVVjIvEhPkCFrEuLUr5ESLmlk7WPHQmbsgFaTbd34FAtw==,iv:mkjStTsQ3Lz+5itSxATHRI9VkKqh8lMof64t4f2INgU=,tag:G4gDDB/9y4Gv3CyGDQZ/qw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:OjJAl1u3at9dc25AY9/IHfJ4sv5MD5KLJn6MXp/ARAVe96sLUq0ydg5lvJI+qM2BzsmulJ2PA7mzoHl/oWgcPOsgBOP8K98Y9X54L8CIPE88scrXCtfj2ocGA6K10gCb5UXNjwL/6s0z7bZlEno0KboxICB/nRftaFEDPPzAJGGOpW/f1/pc9WbvkA==,iv:eFOSWKwbATsdfr/svdQvAor0jYYMdH+CvE74wVhaQsg=,tag:lrMlbVUTqYAhDKQB4LYRWQ==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:0PeTB30DWZVbysXob4GppYXcnU+Ttwe+ivV1iHspcqJeUNu2MoF10Espqcw=,iv:BMY2utIWHF5HcvAReAbihKaB0BEWlgvMbGQqaFC3+HE=,tag:Y52m/7YK8eCkUXhNCgF6Og==,type:str]
  NTFY_TOKEN: ENC[AES256_GCM,data:3/JAg3q3MU2vg9c9mN70BoJ+OhAjZB11Qkp9PW5jq4Y=,iv:yjMw2QeX2ppU69NMIT+araxQA++ZzokUoirmWm+MwcU=,tag:D2zipAKau4w2yoPXFKzt8w==,type:str]
  #ENC[AES256_GCM,data:+UybQfN2EQofKtHBtk0gonLqf1wBhSnPV+ai1phXxxTor9Nju8hX8WyzKB4J2IJuWdWlINgTYWLjat4ve+sxnMsazjih,iv:FGisUqPnLQIQzh/zFTLOPdp1djnk9bxMALwxcZN1IBU=,tag:fnJpwE9Cs//iQqoKAsU5ag==,type:comment]
  #ENC[AES256_GCM,data:Bycnomzsiay09B7+rC35UTKFrABSJc0pgSk9a256Yg9PHa5uiFzbe3ElDHeXjaoxOIa2oKKuSkoo1VfWajaBhXPz+VEZv2h35g==,iv:hQCJXO5DGoucXdZQKoLyOnEACfGeqRfIjvo0Anov+3I=,tag:0ks0ZcVChKWKA5kVwocYww==,type:comment]
  ANTHROPIC_CLIENT_ID: ""
  ANTHROPIC_CLIENT_SECRET: ""
  #ENC[AES256_GCM,data:p+KDJQV5isHv+vUxCqG0GVgTvFaWs/aypob4f94ib+mNOTnjnpRg7ubLNO+a4U5RobPSHTYoj4eyDCqo9w==,iv:xcKsQ8u1Bb4OTCLxZCTXKl/UdST2FeGXsdFrkb3ApDM=,tag:7BqgJHQzenQCLTtC/Pb8Lw==,type:comment]
  #ENC[AES256_GCM,data:eZPyHrlHm/Ag3m0A+dluvxlZivsrHw==,iv:wFsuw3zcpCS9HyvA7oHLdAzUaMnPtV+mMbuUXjLhKOQ=,tag:8a1sZgjFVPYC24pAzuzojw==,type:comment]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUC9yUDFMQW1TeVlPTlhQ
        d1pTVkFGN3UvbmxGT042TDBqZ25HWHhwODNzCjE1MXpORzQ4OWJZME4vMjJuV3Ir
        dFlZeGFtZERjVi9nclpFUENmMWk4L0EKLS0tIEdCbU55WlM2WE40SUhwOTUwN2tF
        bjNhYUtWd084L2hJRHE2K3FWbXBYbjAKMkqWHa5K74zsizEAiD53LT59jsBWQ0mR
        dv+WzsGuL2QwDoQ8fZcIFwNCT3qWzYNG7+Ab1+3p8CkQ+MGCysoJ7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T09:12:45Z"
  mac: ENC[AES256_GCM,data:SclZXuSvwJRTn0TvyIIWzUhCWqKvxhnnpenbk7jdbWFUxokpQEWzRdhUVcDqh4KKOOYgwkZkGQnzcqJ8vVocVkr7Vwo0ni1z3jIu7shMuVwBs7Q70V/rtk2+qAU1Fm8HOcCQll+fIyBCFtfQL1OzadpBbjO50YU180zJ14MzZ7g=,iv:is+KLRItsbUcaCyp6G1AU3d5RwzEM9G2BXblRr6Ethk=,tag:I7lvm7+8N6qrIlO4WhSSCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
