apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: harness-registry-db-secret
stringData:
  username: ENC[AES256_GCM,data:59YTK5Ip9Sr6xs5Ffm+xLQ==,iv:s/XE+0z/YGZWWlyziTug6Eup8Gf6dDBa1LUo3gmChgU=,tag:PcajiIU3IyYq11goH+6J7g==,type:str]
  password: ENC[AES256_GCM,data:3xjC/008hYtejZZxcFBZ98DhXLFyGH40w3DpmTdnegb0+uDtB1GbdDterNgQHwoR,iv:vPAlgPFqPF4Vl35m7ZQJvnX/6e+gm7i9OLTqKFQxwTI=,tag:GOrBOr/JQOlHzz3feHlXMg==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bG5WL0xmSjZ4OVUyVzYw
        bnNqQ1lRa2dKZmhENlZoUXBBZ2lyRkRraFdvCmQxK2p3ZS94amhXQTIzOVArRXd6
        ODM2M0JmZFNhejZzdHo1SEplbnhzSHcKLS0tIHVjRWFiM0dydThOOExvZUE1QTlh
        MThEcnJuUHBNK2hyNjVUVU9kMy8yMW8KIXmgxSVRlQW4WtxZaocyQetj4tshSTJo
        BmD36/xyD5AQup/aPPTLZzSTC9vEDqJnmiLtvmtgKyJ4qAI7tyvb+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-10T09:41:15Z"
  mac: ENC[AES256_GCM,data:uXfwNkB7C8cLafbqgbUi3Ouf0hyAc8L5jYTCExlHfxQtOldiUUn+omwaMkNXWd0KQjpmGmcLTXI+1gP4RJxNl8WdQ5FSlIPQNKIpQAPO+7dtfS5f8Dii+bONJ7Vfr4N0cfR0XT2D5VUVOGQJ2iNcZXCt9qYvPvO5MMqUwa9osso=,iv:R+vWw2htZo8NLOjJVz1Aw8b3hxTEqcb9P+aOWihm6MI=,tag:62ZOZlBODHJGayRgU0jVkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
