apiVersion: v1
kind: Secret
metadata:
  name: niles-db-secret
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Qp6zios=,iv:ti123do+MTcLJddMvUCaxgTnXN29tFGveDS0nrvSViQ=,tag:DvYA7XPciefDtINW58gd8g==,type:str]
  password: ENC[AES256_GCM,data:5veAtd+EHsWgaxjpMSEtddYOrSgnVCrML0GnEFXPRktMBA3KqAb+HOswOEJDtpxd,iv:z648fSu5YPI90bp558dfMwPOSfZhHBglg4dPBHCzMMo=,tag:bhlI90DMCiZ08AqSoWLzNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb3lDbXdnN0FUQ0hLSXc5
        dmh6RmJONmZWTXd2cUFFMDRtdXJ1TGFVWmtvCkxwN0dpT25lRDdJUy9lakF4YnI0
        L2tDcGk4ZjFycytWb1YxV0t4K3VBMUEKLS0tIG5IVHhDZUlNcFYwL3ordzJlUlR4
        Q3dSZmlSUkg1Rmw4K0xaQTVSWGkvV1kK/B4mgTV2EKIhot5uHftZbCahFanNm4Mz
        3K2+XR97Fj5S576heOl3b2WQyFvQYwCJytcHqsCeAqB/6c7AoSaxeg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T17:30:26Z"
  mac: ENC[AES256_GCM,data:wyCL+Z/I1+njGqvlpk/in+eEdOmInslsKvc8W4WExZ4LNTDW5hMqgX3+1unKSrbZUxjE6Qj0nG7PZXwTqqL71NRqNjSUzWyIlB6F5j049qh0pQ4mH3UFLyD0Bb5Oys42bHnmkAsy3mj1V5HUEWaNZtGmJQj1C4z/R6CE21OWxVA=,iv:FpqXcvNnoB1kxu3m5HfYB3mRNe9Sv0utjoGBN/q42Zc=,tag:sn4Kf/0B8ApSz00Mf+s2ZA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
