apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:13u39L/rqgFDLO7OC6UrbfYcKTW5IaAWkDImdugo+rQ=,iv:S6kkbmV0MHX7QhrsYcdQNO55k7ZZD15l+6uQH/JE8v0=,tag:Uop6Lb26woS+Aa/75XGhyQ==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL3NLWUdoSGlpUW50dDFJ
        dXFIRDUyc1pyMlZvckpUMU5EaDRLdEFaZjBRCkVBL3ZLTDVuSHdMa1R2VnYxb2Nt
        MjVrb0ZrY0ovRjBhOHlYUGMrQk4xTnMKLS0tIFB6cHZHU08xSlBveC9HdGdla2JL
        TXJNTW05bnFHM2ZFNU1JUmU0SXJpN1kKCIz9jCXHCrRr2UQNoqJ61MJELyMGmLGT
        rz0Mb29j9CZ8mtxvfrCWTcwWbvq+Vyzgl+EIf+DMKLERvsY1WGEJpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T22:16:22Z"
  mac: ENC[AES256_GCM,data:5O5ngHYRoaliq1hA0MeGR0nCLs9zfjuXvI8pomPV5GbqUW/uNesVaBO1HrPasm42X1pnbRJuaSRSlyCCaAtTwYo/TvA+uqE2/t219nAHy+h7yVjwPtFCce1Pv2ZHWa69vilME6oxkK4oHsqIl8GXt42LGTwhsA+WAv5UJLWlmCQ=,iv:VqjVUOnQMEHeQIVg2whJIKgiBvCUZa+f+Ogd9ZIeJS4=,tag:QBgHKb/60yvs84wlVkFrdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
