apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:XbsDlzYvzqgDKgh4lJjc+UbfWV0EkAAap+egvHS5Nok3+hCEm6hyL+fRFS6KcD/QbRGEF1RwlTs++mBdGEqXtDwL3il8EZIj+IHhZz5leZDcfyiAo/f0GEKmuoEluia5gIyoctJ9qdl+Uz6rWP/9KM0ix97x/f0Njr66uhhHoJ7JM3fwSUoXJyw8gNDaeOvqs92dYO7RhM8d+pBINsiUKMZrHDdR/25+pDl3Y7GcAY5/TxCPZPkf6g==,iv:51p4XAhLkDBuawpwKxKcBOI5zC3Dmcb7Ta+fzk9QTlA=,tag:X84Vh9pk1Nh0TqykGDKjnw==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ2ZKMXg1dWc4UGZMRk5v
        Z3JOd252V0VuVDcyWnNpMEE0SGpoM2NTK1RFCndQZ01wNU9oNnZLdWdORXpOODNT
        OWZNbFpIVy9KSmRpSUxJYjhBSE41czAKLS0tIDY1QVQ1Q0FreHpQb05SeWVJRmRV
        VlhmcXRUeUQyYVBaY3l4MDF4RVJGVVkKlNH/LO/xPJl4Nn5eWSa4hYpXGQDfsvh2
        Kn+W3Fi+mAiePtZVb6GVEglsHw4g82uUKsOy7dwJggXfFeifmZeMZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T15:43:49Z"
  mac: ENC[AES256_GCM,data:asx9d0Y5edi0yeNIk5L/0dyG6NMedc4O1/dr41j/uYInc5A5mLt05F+kwIyaiXrriy/e0N8ycoQ0vnBLQqn/DZklnzZP/7LhXg5JTa75fdmxmelgwnBQMX2pvYEejeHZCT/fIuDe438JptPmOre4wPWDRtlFIeqlC57mewFChKk=,iv:Q+L9ntdTugcUwNVs1j14tb1K3D1x6SMjJaANtvwK9jQ=,tag:azruI4YylFftmsXJFim0nA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
