apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:UMYsCJxWvFoL3fQ9l2X6YjnGNpVnMzkb+f8YE1wGsqvq5+n1Mi8YI5Mp6WfnK0EmVNgKrE6lSZ+cW2Jzkqvd8igyfSFDINF3Qbpuab+8+af9tyC7tHWI6JewHM+SRtsvIZfMMQzUTQWCus2ElyiYdGniFQNucfqlrtS2+mfpoVNT5bPC1X6xD1YwZyctPwj8UE1rvkHPnlAi74NxLAMjewG1Lg28bmvgaJw8yFRkBnFh69da0DBRVA==,iv:PwEXi4gqqwXV1uWlLftNy5V+9TTuC6gkYrB/G8sQDnw=,tag:wgxF0XRdql4NddpgciWbrQ==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbFhSbU9HODBqUE43OWlI
        emxTTTcxWmp5d3Z1cTlNVzFnMkRvd1o1U0hnCkZaL3MrTVZFbkRtUDBHTGdXUmJ5
        SmVSQkJYOUxPOFVsNmNwdkIxWHBib2cKLS0tIDJtQlZicVNSVWtLRzc5SlZqWGI4
        OUZqWklHdWdiL3hWUWRrTDFZZmFjMmcK3AONlfHEp3D81Pk1OO/j9rC09CN3nJcn
        Bv+rLYAGJwRmOVb0I8rf+IZpkMLTUZhoTH94wkG9lNnPsZ+dbVug1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:06:35Z"
  mac: ENC[AES256_GCM,data:oDg3HIayKnn5GiRpydXUtLL5lU0n4yMTdmUujXaSz9CEUszbTQ8Q1zjIXM/p12u2MUv3Wz11EbZESohbcRtdOPPGDspXzaVcDDReBJjs3Nj6jhKSVORcDHszrBrBCjxai93+FXeqZSPqawvpY52V9TElS5t7k3EkBGVcWyBKi2E=,iv:b7Nqrzqb+EkNxAmBaK0t9BikWXb0VYMY0tzTxMpsQyM=,tag:GyvvdF9BDvUqQQWGm3XLbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
