apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:2CCBvOkc2OsqZS4/6DQffrK5QSSXM44ZzDtUDqgbbVnJBdcHVwI2vE1SX9LyaFZxoA5Gvn4aF+qCpcwl7yHbP7/+McbVUZrfS5Ap9TBNl7QjuXftrWz6Oj//5fR5020/AifbuIlFNVYZf95E+46ixtILlSnI8fRA3/Qwcgk4oUyl+w1738q/a0Oub98T0T6/9zCPABqekHVZrJvzg0WWJ5gFAou0NAOVGmJUG63AoNi+mqWRmKxP0w==,iv:LdqxvDomxtLbFwVJTMNG1kwnMknLmG3CCHlUcbh2MBA=,tag:7knty3vy0sjCT1LMkn+dyg==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYWhja1dkekRwTE1MbFR0
        YXFFL0xDTHZtRkViVlZxTjlUeGJVcGlVVkRnCklhb2F3KzRuT1hjS2xUU3ZRdjRt
        R1pJbWNwancvaEs1dnF1TFR4ZGsrRTAKLS0tIHE4RkxlUFBGbHB5NFNyTkMweFl4
        V2N5SnZqR2hySDZmdjhoTTN1WnZjaVUKlmCVLGwxAxb2J7WiYEYoo7C9mZHilg0q
        d9UBiR285HqIAMWra5xai3MMTxb8a4sgpevPEwp0EUOSwN3A99KYZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:33:28Z"
  mac: ENC[AES256_GCM,data:jZbhkD8KwGVa2yN3LRelRdB2QRJ5QLgONLCbTvYrYqoHzPJ2mcj9bAE8kQi9cHinlhIajVBNHch4ga+jQB1Ucox1U6ypTnr6tGinVmk9PMAwGrkIApQNJTARJC6nDT0XprT8C6Z7AFZYQEJ2QdzZ4FPgg0oQcmTq0LHTtSoU4/8=,iv:1At5ircF/WdWwvsWHWbWA2nJJzHHVj2uVGpnW7styXA=,tag:l/iTGSlSBkGAmVvxuelJUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
