apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:ldr0FCA30anl8uP2OMI4SLWtP2i1YHGLMD6Y8cHfuko=,iv:ZVYdD4jth1bWtrfzfW7rVZVAut0qrljsnMhlSCekf/w=,tag:wYyBjwxVivDTEVoOmrYVww==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R3d1ZWJUVmFaR0xzR3Fy
        Rzg1QlU2S3BRdXNUMVRoaDMxU25QMmhUU1N3CnZxcmg5L1ZVSXpwS3lXbU8xL1d2
        MjBzYWU1MExWdXB6M3UxKzdtNElRQ00KLS0tIHJCSElQYkYvYjVadE9tVktkNnNJ
        RTVIMWxIQm1pWEwxaDZ0clBMZXRhbkUKhExaHeFzM+htwJ45UTbe87yTf76erQzP
        3iwND0oICMq56mLGnIQuxaLrgcwetfTh18shvdr2LCGMZ0baqsHzTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T22:16:09Z"
  mac: ENC[AES256_GCM,data:uudbotEu8CWyA7BIgo33ksshhdTYToAgYv951PCM31BAp7Jd1APtQJ40pm85uKj1UQ9UAhQnku68XTsgU8wAli+rRpvRXkLCsJpPFVcYA1MDkooJ2u2NqSWxjDPMpEt3Lhd1wPwuX+KyxIqktlaTO7qvDg5wkSZ2RG/jPs8oJkQ=,iv:WmybuNjCQNnXJHP/R7zTwYBlVOYzpU6078743yP1yCM=,tag:rcHf9uQsdlE8VmGFGx6yPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
