# Fill in values before encrypting with: sops -e -i secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ticket0-worker-secret
stringData:
  REDIS_URL: ENC[AES256_GCM,data:rf2WaBeZSyqpCLcOVluZEuAuhIpoFSURnzcMIAHJFuOL4iF1G6211aUjTkb9z5MCYsjLXkAo6mguf598V8OU/PWHjUaW2dcf5+kW3QWQmuEx4C+l8UxI1PjIDQ3Wl/mjDTFTgkMhvtPaCtRJKPDzjfmiqokATimNhfQVLEWR5TE=,iv:pLE9glForCrQzj+QZX5IpeSnG7oI/p/VptjxiHII44U=,tag:qQe9T+nhZ39Vtpm4ZQq++g==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:2glkSLdmXxOl0aqySwnrq9MWM84DbLrxNHPG4D0hJGkZXT58O5lKSpojDBHpmnvbi9KJoqLmvJygSzLRFbDDDivBFWvY6F4xiuU9nmf25m0jwjg46sYbr0iDOSANnx0xS8CCpaETjLYGzSMvI/rNf4/Utv9sCwO/aP+hUQO+sLLfTrGdMr5tFRu5nvYeUE7Ln5iCC6jB,iv:xXt96IqGqeDhQSUQN0BD2p115qpTqHC3sxxBG0qemQY=,tag:R3mODA8wCAF5rLnlNLiRgA==,type:str]
  RESEND_API_KEY: ENC[AES256_GCM,data:l/aCwjAhi15a4/L9cDdwcxeU1lJbFCA9hbG/iYu87hlLPA/6,iv:qcqwbETEmZAORyXbNxxjzJsudNm9M7p9zYGAkTCxCHA=,tag:GN6kCOz1kbY0Jl94tXFDwQ==,type:str]
  AI_SERVICE_API_KEY: ENC[AES256_GCM,data:fxi49fQZ9uYEfl+Add7vJrASVNoH3PoL6BUACjNAXr4J+vm9eUXLwq3tV+4=,iv:/SIZVREmp7QLZ5yb629kYdoqoysDTNcE56GiSUA/FgA=,tag:cYDxevQ0Zt5+mJf/kBziFA==,type:str]
  AI_KEY_ENCRYPTION_SECRET: ENC[AES256_GCM,data:KTF1+l/jcjStIX96RDK6KULHxArEjtiYGKLCfGI27QuMMuXXo1mr26mOq+rfSRIkgaA0C4gnji5Cg7gN1EP6Pg==,iv:MyLP1p/KX3l+Hwrrd7P+cIbym00zenKU+rbY1KL8Boc=,tag:q8UMdLcIkPNMDYeDqpknSg==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUlVrclpiSWl0MWwzU3Az
        blZGQ21xZ3cwRjdKbTJjVmkvSXoxWFJnbEFFCmFVLzlRSXRnVXVjV1kyOGZOVVMv
        cGlmVzJWcHNsaEhWQ1VHbDhIMGNoQXMKLS0tIERaNTBFb2dJM3NuRDNCSElFV2lv
        c0hVSTVoSFkrMEdidFpIMnAvNXpYRFUKvqBzKaq+SRwU4puJD4pTuJSZ8n9GgCxE
        7PH5HmbmaymeuGT5YIYZ643DMTy7FlvxYueAUpMghQU/cde4sOugaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T09:47:39Z"
  mac: ENC[AES256_GCM,data:yBzpj0fWNHIRbjhid+56eiKqcXbdowaYLznl9Jjdru59E9j3fZgOhG1kquQ7lKtXmwMfSWf6kb/GpDbOszOstf655A837H3gQ2zLp1DQqN1ecgyfKYiSCJVGCTbyBMjar4mrgN9Tped/C3o7d0XHgvKyf4qYsAboptGz8s+ArQc=,iv:qDpW5VWjDFoMliTySY8evyzb4c5RYWEMJe7L8lFrLh4=,tag:rmaLCOyhlWYQSf1t6QvIAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
