# Fill in values before encrypting with: sops -e -i secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ticket0-worker-secret
stringData:
  REDIS_URL: ENC[AES256_GCM,data:Eoo35vIJjd/KNJKp4zYoDB/bLJs81qEjw0RXudYwGDJ4xRxKahw7p5qBy6XvZdxp1aChCqfdV4poHo+q1wMaVDIgQn5QsZ8Pi3CcTWTQgBfrhgt9dFV7ZBF26oNmuE5OT7Yz0jv0KTkDn+UUiVG13r19xmLt1f5X/vAXMUHs8Eo=,iv:VzOOXmjkw0/oJVrGZNikwipze52f9TJlwEOYD2qhvCs=,tag:6oejlZfoJ6nz0kOBll6x0A==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:P+tXgXK4jv+TkXa6xMSWkUDhNB2/bcx7XYjA1aEN+28kiFGLiSM48P7M6laLzlZ2qoykZw2mxv3RwIPH7nx/0Dd+Bgxr/7jAgQ3C8UjeoN1wOSTmgw+Ps0PXp+cOJi8/V5hia3uPKCkAKgChda67xdfZ3SjZs2jaJy07IP61WX/yo5QJR2j33Ic4AiF6WfU1AO61iMYD,iv:QZS3pYNzEQxFpthKsfeHD1KqWJJT7WHVQ9e7hDt+3vk=,tag:mKnB3daH9xXN2KdPVvLrJw==,type:str]
  RESEND_API_KEY: ENC[AES256_GCM,data:KvMVnPxSavVelg6L4Gvq1c3YVbl8ky7JLBtnNxgH7iPYOJ4p,iv:1KYrddNsnoJu0jtwxjFfpaZmXNf4xlmiT7zk7gB4lY8=,tag:9PgxtIf251Egm+NNoS8Iyw==,type:str]
  AI_SERVICE_API_KEY: ENC[AES256_GCM,data:F07nDdldxziJCZw1aAnrAG0OizKFGwGvWlwkZ0HurGUfYNIKzOZNqmykaE4=,iv:+Yey7KGIdp5ldsN7qW6C2u8rfL5uB79ELmINnfhHK5U=,tag:li+umlAYgWgbFPTroR3acQ==,type:str]
  AI_KEY_ENCRYPTION_SECRET: ENC[AES256_GCM,data:J4jeXBS2bI+oRE3Di4nvRoMj6p8aqhpnWHxyL3Ia4JF1I40xOJD+9LhrRRP5UrC9ztgyLDibiy6c4VJywCjmeg==,iv:OUJQREuI9brjKcemdOQ5uXABrxJezzOyVosKzA7hGXI=,tag:KirhB7EoRAaQGZac/4H1QQ==,type:str]
  DOCS_INDEX_OPENROUTER_KEY: ENC[AES256_GCM,data:iRQQFh6SPohuS8ITdnMXUiTOdB6tQi4rVG19Ex/hzwYIfA/zVYKKy3gHBsbVjSMjxav+uMkCpTbvNyHYf6AVbiNq3aw0xb3Xwg==,iv:hVGq+pwC5Y7+npf4LhOOaEPNir6uRJOxOKjD9hC1AUE=,tag:hQmKWFzjASaXVz3qs53lQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNURPeDNETDlXNnMrUnFj
        cDlnR1Rxd2VESFVYeW1uRG55NWZURE9qajM4ClBKUUdPUmZoR3JNNjhJamVaK2dy
        UkhuMVVBWS9VRThtZWZETmpMODQveUEKLS0tIHdpWThEYlYva0duM3ZSN3o2SE9a
        L1FFU0hXS3R4cEtMc2lzLzYwVU5zaFUKpQ81AQqtWvhv+icFJ/lMR9lHMLaUQPyG
        X5EC4r3E6SCnmXKrhsx4yU10LTc7twxTtpU4gl319GQ1yedvluCvQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-06T19:27:09Z"
  mac: ENC[AES256_GCM,data:9R8cyLnQYlUbMht+gC0frr9u3epxA9FJOOaNFQHDzLKy4uFs2oBYgc1zJR1ULNi3UtUDgMZrpNe9MkElRjqROKKRDNPCS9QQBmbYliHQHS2XW1IbUew8RD1f4/SpZihf+Sq04RLa10odBGQMoC45kzMFdoqrLYT69Hbe2pAHOXQ=,iv:NCdC1N702iRTTl9TwaWvGdqc3EheG/+AnQixQJ1MQU0=,tag:WDRKMcFDNAAD+sD4K56NEg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
