# Fill in values before encrypting with: sops -e -i secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ticket0-worker-secret
stringData:
  REDIS_URL: ENC[AES256_GCM,data:8X/Fatm0O1LmzVxVi+8JFRwOqBcai7eRu5ZRTd4W8zvEIK87prhtksbh0Yq1QGYvLOO8Yndst9xf8R0RpgkQtE0irk6d1sPoOvTctZpAHagfoMP6chT9lLKzEQbErSzTHV8iV9kybz5vUp4oGo6HAW0zv20Z+DjPIr4p9xwUYvg=,iv:WlDOBQqk8gYCQ6r7mbpfe0nDKgA3zflVItu5N0HdBb4=,tag:YO+ZIRx7a819BKDDP6O+Yg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:Yui/tgnY0Cy23wamN0tdvtF3zfpu56SqM/PD9hBa63Ju4RK9H1+9tSzPNrD/wwo5E9gT2h+Sx9vX4hCXgyVY5LWWz4t6p5pZFL8dedGkjTb6FnmmL1yHGy/zLFSGMOeAn17qYv8ureStvLWf0i//3DH02atxa7T9TDHeQu289cSyjMjHExVs7wwlXKMZfV2pn2p9Iopr,iv:+OzXCPFTHY/dVl+rlKHCX6yggQ1s0D9dTXykqziNMv0=,tag:Q0v+2o0mgAGfLFgNKC0u6g==,type:str]
  RESEND_API_KEY: ENC[AES256_GCM,data:6bBsDM/Z/+QD7+FU+48SK1GBNObGfngUyx1a8rRDNlHnOVv5,iv:wiwuEb/L83gtGSqj4fC4ETnrbxFqe9+ntvTjSy8sTTc=,tag:AYiyxtaH4pZP/fe6WkpMIg==,type:str]
  AI_SERVICE_API_KEY: ENC[AES256_GCM,data:Ahpo8Ak7tAK6t6NKc+KEqf3odaP5I2tswwp7iM4/K0BsipX8hGgiQBzEI3k=,iv:GAH6z5QscQ9NUrr0W+2MZ0oWntstICflNlbi+IdD3cI=,tag:mcNBxfLaaFGfsv1T9n597w==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibERocVo1SldZOEhneEht
        dXJZdnE4aVl5aVBaNFltczVQK2R2RktlT2o4CmNPVnBzM1E3NE1VWTF6THFNUktV
        dVVWSlN5NG0wK0p4dDdxa0YrcTV0c1UKLS0tIGtxWDU4NTBOanorU0RIMUhyQWNT
        VVY5UEJNMmdLazhBd2lzbDgxNEg5bHcKwCK66ZySf4Z2B7bWoae/AjVerKZdOV2B
        WmAk0zBk5JKcpi/1GS2k1WGs975YXnqzLrTF+y9ugKu/CPYKiGYn/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T16:23:28Z"
  mac: ENC[AES256_GCM,data:G7i33ai4iMOrIW7vpRFFKa9jurr3zajEveYn+dGn7h/iThmTdjWw/6VuQWgDJ+FX0RtD3qJoLqVCqGXD+GO9E3LQVB4jG78h8/xYIpUpM9CxH/rEkE/ExJJdklFlShzGiSc6kFGBynVdEIg5tKnxEKqNGtnWAPYIw6rUTDguiis=,iv:lhWupdhpD85i/gTBMfiN9Hat1idDtazXNFmduSlpIec=,tag:zfiTP0rPbWhU0PULeoYByQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
