# Fill in the API key, then encrypt with: sops -e -i secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:HhbkgUrCgT5K9THksLhr4NAEQBulavpWiKA9JjiopUk=,iv:mOzOjDdeYAYxwHFY5RHatTIZf3B1bh62875QCBeNDUM=,tag:PP6cZJD2qIVALfum+j0/XA==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoa2Ixelc5VzgxUnlNQXVt
        WjREM0UvTml2WTBTSkQ0VHpQdmNJck1YaTJBCnZnaDZEd3k5SFFaeWdwdHN0dkVl
        VG9aSEk0dEVJZ1pXVk82R2Y0VkUvVEEKLS0tIDc0NHBhQ1VFdTc5dm5ObWdJYWdZ
        UGNDQjBjZnNlc2UvZFpZcUZ3MjdHZlEK6YSrAZTwOk1IIL6H/9SPBVqrlDXRNtBf
        MZZXluQWtvcovw/OhDRNG35kdkEuSriE2Vc1mTUNVuHj2NNIM9G27g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T17:19:51Z"
  mac: ENC[AES256_GCM,data:k+3b9508ee3RZLBflqIiKbmtOMPYdrDoYcYqi7YdPyxgXHJxsYqi7d+hU4WRx7fgReHuEdhQ/Y+1oGdZD+JYVY9Ov15KF+daGKiQwR4lehTWtxvUSgN1z/eyjweoxioaATBy75Xh5BfpdSPc39FkhuOycJ6WyFQZoAHBLujSaGw=,iv:9wtoR30GdlrI4g2bAwouo4AkWlhprdLHNGr7AOUyAKA=,tag:Tpl3Qx7GXdHuxr+8wkX3tA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
