---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
spec:
  chartRef:
    kind: OCIRepository
    name: bazarr
  interval: 1h
  values:
    controllers:
      bazarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/bazarr
              tag: 1.5.6@sha256:79fc37491f55c7e24427bcd669bce3df2d7415ca432a47ce9d53cc5988af8411
            envFrom:
              - secretRef:
                  name: bazarr-secret
            env:
              TZ: Europe/Copenhagen
            probes:
              liveness: &probes
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 6767
    persistence:
      config:
        existingClaim: bazarr
        globalMounts:
          - path: /config
      media:
        existingClaim: media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "true"
          gatus.home-operations.com/name: Bazarr
        hostnames:
          - "bazarr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
