apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
stringData:
  BAZARR_API_KEY: ENC[AES256_GCM,data:ijkiBzTpzHh+pazGPnSZHHUQMl4j66HHh0Q0IbXgKl0=,iv:1JDnMO1quFS0tXd66hJL329HvderfxRq8DY6SA8B67k=,tag:hlSKd3OkDvi+9RCnBZeU5g==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZkcwREpacVord2xSZ3Vj
        WlEvT1dqNzMvTk5XaUtLYkRtL3k0TktyS3pBCmxWNjdZZkFyQ2lsdXJJYVh6VjJU
        R3pQbktIaWtLRG9CZk5QL3lha3EzS3cKLS0tIHpDcENXL0pFZWpqUWpzTFVSQlQy
        UDByYnlIc25NZ1ZZV045V0o3ZDdhcWsKOzOhQgbg3qLoB7+55/6ZWpWl3FAgWbJi
        2Cfo9Pi/GzL7bbitVKqZrKddQZP57UAXRXdWw31tj/D+QUQnB+LRYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T22:16:35Z"
  mac: ENC[AES256_GCM,data:mS6eG579ARt75IFE67BdX0Uz8HRcP2H1DDijWw7B6VVt3lZB3OUF0cG+WvzhPMH7inTlaKkYO8Y5h/YqJkCCjYJR+ZLW4CLUZ4620HdauPKHdRbNM1QuW+VPzMmhN3nZG1v39Ep+Lxw17FBSyNVHm+hKJl0coTrwRe7325ZJL6Y=,iv:KsnM0s9bms0QKpVEC7ElAEeXKjjkZrJKVgDCepLkYDI=,tag:wbTiiqfBomVpqtsh0b0zJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
