apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NiD9ZKKu4s1aaIKVHmmgmAXyR8j8Iogbp4yPoTGQgf+F08Eoy8K8Vw==,iv:y6nxa+6nNNten2bElUnr8CM0BuvwuNX7k8KmDc8obuk=,tag:WK+pp45tl3hX4Bs1qsshuw==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdmlrUFNlTit4SUt2V1RE
        bStZaUZkdU1rb3NpNUo2UlM5T284TTNiYnlrCldFSUpuRmlBN0J0QnoveW55Z3pp
        b3pDUzN1UjV5bG53ZHE1S2UzK1I2MW8KLS0tIC9RSlhZQWJPci9zb3hMNFpkd29G
        VFcyU3grM3A0VTYvd0dtWm5YUVNVbmsKneQe08ZZChUHrQhW8eaV+/smHIqgNm7e
        QDJ+ndLgsVSHr9nfawqK9dgaBtT9bb4SWHeZA6fqKXjhbIMgpkpfKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:07:11Z"
  mac: ENC[AES256_GCM,data:R8y0qa2qBEEYAetAGl0rKAht9rfFszMy42GAKJEjKz1kuoq8yq97iuIuG9l4XxYYr1s2N+91lNNrV3BkHJU/YeRXvR37ytp07CkwQNZdI68UydVczR3hDxkVoaiqvOPrIAIyzNXQVkTeetQgVL0g7QrvMfhO16J5aMLMF37DTn8=,iv:J3eRwaqRiaW08cacRnTyCNBV4kYoSNrhibpDOvESHPg=,tag:6evKha80I8/MQz+Rxf+e7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
