apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:aYv04+VzapU7DfAcm1Mvu34hhi6LRDEZwx0yQ2AJjOSpKmvl3KWs/g==,iv:B9oeX36BBrqNWZq99reqNzLzvx5FlvsWqwTQ2kN9f3Q=,tag:QT3tuTKZ0NrsMojtOOz79A==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdFR2aFZlYk1Bem1JNE5z
        dXgyRHVLM3JGVEhDS2k3SC93bE5maldPd0NJCmJlbFl2REFQVmlZSi9yaURMRFdX
        RTQyRGJpaXE4aUpjUVZpZG84ODF2ejQKLS0tIDNvb1dwKzJyMElHMjgxOVpHOXZi
        clFDRlZqUjR3RzYzdXl1R2FrR05peHcKIiFc+RS2xYtQwcgRFdXqO9bx9zNhwIL8
        pO5QBFQP1tYod8ZPBHe2iKD4i+bAwOuTTN4WaYTACRGpOgE4JJJSYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T15:43:49Z"
  mac: ENC[AES256_GCM,data:PDs/yQDnXeAnSP0m78Ati747kkjxVS6rhhEiE/eumjLPI4ibl8pgL18k21WrQ++hvRsqDiyuitn6O8ogktUnXceiIjKqNcEYmT57qVew7h+fupG32QEEeL78jGrZPe/tHglH8QZ8L+WX2uddcrq8hQF6DLZqW0R4K3rxQVaYvKo=,iv:SaPZOJKhnMhNdr8R9LLcXNt4vLTNwFBNKjaqJIcUQp8=,tag:iOKZqxNAI4VagYEoxzBFFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
