apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:/AryQ0cOC5SpWCt4l3KETo2Sdi7rd8SfU0jLZ1ukSqy1rw549Jf9WA==,iv:kqBpM4aEJ1JbsTU7DBPiFm85nRCepEglIJshDKWupHs=,tag:OWveMOlohvkYhL+6mlzuUg==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR0dML3lkQ3ZKU2lZeVoy
        N2FhcGNPMnFLSzRPSHovSHRlSFdsR1Z3WVVjClgzSGxVcjZYNmZWSjUwRjBuNFly
        UE9wdWhOQUoxaStNUytaandhL01ESVEKLS0tIHpUMzhvYlMyZVU5a1hReW4rQWRi
        T0dCLy84NGpyN0tTK2g2Q1ROaUxvTkkKS0vRclGtT3SzDLiKoxe9BsVgA4eiLXUM
        CeBV9dJVyP47IgnJzRlGItH3SwmO8vU3Qwj3qPXR28hdZ+c8qqqvdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T16:33:28Z"
  mac: ENC[AES256_GCM,data:sm5cfoCCznaHaupsGAzQN42KQtMdtoxi739WTHkJgFzEAWCE6d39wfaBisGurXg7HtDMd8afHiXCCWfKwifQGHf4aegxP0i28z+FryWyZdDAOz1ONct7ywCeGyOkaV6ATCyaoa+fMEGxl7SYepPsZj3rhf6ffR6hD74ATRm0dhI=,iv:N7iC9TCn4DvufCnjonxLnTi180Rwy5kxoF4llTbRw9k=,tag:WS3dH8jP0cXKh8PaGvkhMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
