# IMPORTANT: This file needs to be encrypted with SOPS before committing.
# Run from WSL2: sops --encrypt --in-place kubernetes/apps/productivity/wealthfolio/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wealthfolio-secret
stringData:
  #ENC[AES256_GCM,data:vjeAMkgFfj9ZqzzeinUDQrgUfftsJdJicVAt4YhzsIe6CPDRwTN7Ge+qTomCwbSc3PduRQ==,iv:VZpeKWSOWCMRGpzzbudLfaSa/KawmaCDy4GxI1k5CzA=,tag:bOL6xeNaqZDj43a2kcEL/w==,type:comment]
  #ENC[AES256_GCM,data:p423jyDejIZleY1BHO7DIYWu9Uk5pK9SaPfZ18SjITF7Fhn75QvjknW8Q2scwrQ4oho2KgteyI2IvmLm9Uy8EMhaNKb6vlE=,iv:p2LOh9Ovb3JXLbE9OSm1kAoaFH9XLatOFBKzHOfJKCw=,tag:Z2YKJShA/X5RPAo85EbI3g==,type:comment]
  #ENC[AES256_GCM,data:CuWNKNJWBdYI06bqAYS8QE6S0Eds9MZSO5e/KSzN9lbIwNFOq7Tu4upH1jytmh5Xs8rz/6jwWrg=,iv:8mKs2h3Z7679ayAgi3FSScIbbMUp399JzSShSCFYmZc=,tag:SMVr5lLp+2wO+eqzIHEAeA==,type:comment]
  WF_SECRET_KEY: ENC[AES256_GCM,data:jiIfkF1ZxODw54QBZ+kPMc1gB7eTH9zStyM7CGGURdUZRMKAyVjTbm0G71g=,iv:INSZT6zQSXSk5MgDK9MW7eOREuEZO3T1okmg1ym3TL0=,tag:18t4MgH73Tg9obL9uPlIXw==,type:str]
  WF_AUTH_PASSWORD_HASH: ENC[AES256_GCM,data:Tn69J171f3zAPTw3Lnu1FfWCxAtcORxudhlrjtvnzBRrayMbyAbE72eAo7BeNjqAjushzmrveWmmsMZldRnLlyFan7kPx5Gf5HOqC05w2VzhHpP5ec7O366UKin1mH3AXgrlvmc=,iv:HdxPDDTyC/nH917Ukih2MZHARdI6Nry3if2JYe9GaY4=,tag:UoWrBG+U2OFtF5NpghvSbw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWHNKRDYyeFpVUUxFVVVM
        VnY4aEovT3A2Ulp5emlEL0V6M3U0d1JGNXlFCkpNKzRseFhXeEZ6d3MrdXR2dzdh
        ZjFzSENFaG5JUHV2N25JY2JkQlVyd3cKLS0tIEI5ODMyNzJVL0pNejB1VlNkMDJI
        NTJ0YmZHdUkwSWQ5WUJHNi93dTBiam8KUzhLMu1uTL0cbnH67cirL4NWaCaPSQpl
        wYpzMBVdljlDjsP6TEkQ8+CZoRcqauiTi3p+AH+NExn+QtaKXPnc9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T16:00:58Z"
  mac: ENC[AES256_GCM,data:/7hGm5QXWPc+Z5jNAjyD6R9JrZq6gGvSYqF0ScBEGJSdyPRBTVjLy6ZFGonnz7lBZAh5Bc3SO3KuvaHavE5x0lec2ZkTGKo13qTmb80sGdg5bHf9anG+r7ZNhGSxxH3WqDIYSup2qVvsV9Z4nXSH6lCHthBS7wazjYR2njn3WP8=,iv:rCZV1HZsNgyTE4migwIbEM7yYvFeWUHzLwfONZ1P3Ig=,tag:x+itmqKpdVplMWevs4ADWQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
