apiVersion: v1
kind: Secret
metadata:
  name: crawl4ai-secret
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:umN9Nil2b4f6wLMqFCRi0rT5xHz12zn0DAKYvRJOwpJNk4f16zPN5XMWLfCdihHb8g8k7llqqy6CBVh1MrNKk1PnG9OcULbKFuXidsfa+7/aQllv7UPSFWan0/pEoSQIO8zqyTDqAvB1TQweCT68PN4FDN0UBVRJ3IXjrvTNnx5evoEhtMVmOzAq3nxdGxZQ7Pn0cqgaXjILB5x8G/GhEmVyiYY=,iv:EGxsinfaN+f95BK/43YCohZqrEYj90xmyQ3NjiTzP5I=,tag:hze2we3H48uW0GOnTSxVjw==,type:str]
  CRAWL4AI_API_TOKEN: ENC[AES256_GCM,data:/a1wH2eI3n9fJq5+PI1HQxfNtJ/C72SgK/M83Ws/eOZQjruWBTewOiuT6lAJQ8CO,iv:ifpexlhi2bksQrNpOd/trPUfJYp3ZwWmlBNjvB0h9UA=,tag:Z7aShEuvuI1JWkZRC2JvYQ==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eVppU2VKbTJzOEhBekNO
        SHNleUExdVhsd2JzVDJtZ1NVdlhUWFdGVFdNCklWbDNwUytDSWJUWjlTU1UzVk1S
        aGxuL010ZWFmWUIwZEwvMmd5Qml2bG8KLS0tIDVJS3hlOEh2NmJheTBxTlBweXVj
        RExGdlFVQ1BINXBkZXZrSW81cGdoZmMKrgIms8o2SoEWm/PaIFLkfYjZ6YwPiXeZ
        IttNbHlEUCz+sS1FPS3LEeYwpNqMVLwwfoSHBIvA0ziCUqwOKDV1AA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T17:57:51Z"
  mac: ENC[AES256_GCM,data:wRIMQb9Zehwycd3lms0Y+pCG47byN60d6ELuVhwTwVSp6toFEmUdAfNsEc52A18noYpy948PWhpoun1lQD2Hv9wSDVuS/rufH/ixiHyhtup4l+zzDqYsBvrgG3jpxKrGT2RAeCQ2MqyXNXCkE+H+eHEbe8VthWhVaFJinaALIGY=,iv:8AZlgYLgkAn0ecxGVnSsZK21TVl/pQa6mo0+F9I2kKw=,tag:Kdcj6f2PL7K8OVSbpJBEJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
