apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:jeFIDblSW4kToGeSUKsxKfSmfO0ch7hnMCY8PH1v2ABxzLspfiDf1vngr9jEhMHN6QtVQiyuC3M1ajzeHooD5DUbmVhQTzOR216uZhg+RSgH4ZKJpA6fH1/FbYWB6lo6kRYfPIp7,iv:hVYRKW8xV/0YcekZAB8KpAGRetrUzp8ANS6jV7EnDKU=,tag:zZ11m66IwP7IIVMuIoofow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOFYvaVhMZDg3dzVwMS9F
        WUFDVkxNM01sbmUrREVvSGlnREhYWVZvZnl3CjlxNytYdm5JL3RhTHdXVnllYkUz
        VnhCUkxMUWlMdk1UbC95WDk3TVhMTHMKLS0tIHo1K3dKN2xtSnE1Ymh0K0ZLWmx4
        bWJWVjMrTXpYSWJoMWFrclh1V1dLYU0KypBAmxf1HRLEb5tMRMn5M9+sh/tot+zy
        KIcYN0S/8okQwiISYKl7zIR+nx7n/r/0vCSFJ9oTWgoiXs/EcbT+hA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T10:34:21Z"
  mac: ENC[AES256_GCM,data:oTuMhXc/T9axsjVXVzILUW+eFCuZu3ybQr7wcqH+lhzBLn+qx+sqS5/gRKC3HMz1MjECbtVep/C7Md6x7V0zbSJ53YDdCpkojuMwmzvynu5wqzOv+dilwZTQdzzVCkP2vT1gm2dLZAZoF3mXvSp4vH4yILhzoOWIwXnYN0/QZwM=,iv:XmWhnGdZEVS/VtQVtLH1c4XFBFOvkW784L/EpROZi4k=,tag:FUlO+MnVZeLGnsI4IdTKVg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
