apiVersion: v1
kind: Secret
metadata:
  name: harness-registry-api-secret
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:bGnYDTn7sHjv/xOeA1kqIMyfUJiHg2Udhd/l4voemZRXsyzogPQd5S9urVgRPatFbT0mcbuXEvuFDqoAdHH3q4o5c8fLMrGXQnPno1baEXV3pzSKwaeI3pYEf6KAw6+A5T1RiD2+QwZWpksSwhg9QZDgt5km1PLkClu2mnmYMM0+Pl1b9fr+fB+ZAgHi9TAejUeJbTlk/lk4/p0=,iv:fxC2LNXVl9PokI59Zb250SVSCAIgQn+QcRa/YiKTGVk=,tag:QYERFiGwaz0eRh+5KmsedA==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:/gkp2T9UJKZfXrcOktegVseTzELCIhqi84EJPuze16IdjxBNJbOeppurAflvlYhxNp7tNJm7fTWPuHOJ9K0eyw==,iv:5lhk6ffttF9NojLkZYXfDlXwIagvN6DO8eiCFoxgyvE=,tag:E0RiPlMLW1PcSH1YqKK8tg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SExIZjlXRnpIOEpIV3Nt
        L05CK0F3dk9TcTBYQ0YyRytWbUYrWUppMEhvCmxWKzE5d0hzeGRpZ0pXMWh2OFF6
        RmxqY2Y2MlZoWk9lalo2dXJKb0xUQWsKLS0tIElGQUZGRVVCbWg3eGwvL2FwQXNK
        Zk1yNi8zczNVa0pRZFJTdHprSlF2VVEKZOmPnsiJk0pNMQl+tOhUDxcKoNVRVVSx
        owrOHIicIosqnbZzz57z4i/J++TGzLYlsp0rjM2FwlMfhc1VQOwhDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T10:34:21Z"
  mac: ENC[AES256_GCM,data:NmbYg3F0NcsJOOb6Ps+yNlB1YGjPFli7rZssjld/lKkJ8JceISX1nuWwkSPa0+aE3920IXJSNGA3idzLzUcrF5Z0v8fSyaayAAuv5cL+QGgUtMN8dnsbpWvH9HVyttnxh7kSY9tt41lhh1M1UQkI2wT70WqufHDKyIoRRtaxEkA=,iv:HxCBNXmzuXFxrQ9ou+q7C+vuYSjR1RtFp4paMdL7EwQ=,tag:k+4dxgztWPIkqnivB41+Cw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
