# Fill in GHCR_TOKEN before encrypting with: sops -e -i ghcr-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:lgyWFTbujsWOQi5O67IGaWBq9dBggq0eDteXKAY3NdnEXwHWOYYhOgHwA1Mjs8r0ueoWb9hHGWtzFV+pVwVMf9qskiOwi570GZO1GzEPwUE8fSPpLnUTT+6M1MXAUl8L6t6BfEH8,iv:DRGWH3oaft0alkM7BrdYMsN11AAHMbbYkd6QH5uJA70=,tag:LBUc1e9Af71Rpl5Y43BedA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbVp5WE5nTlpZTHpTc2Rk
        ZTJ0WnVPSzIwcjhQQ0FuOXgzbU5WcmYxc0ZBCjJPY0prWnh5a2VpZCt0Q01qdTYr
        em81RG1kbW8vc1hlSW1kYkNIV2pzOXcKLS0tIDZSZ21kWUs3VU4ybE5TNm1mWnBy
        TE14c2VvczZYVmUyRUNrRFJzUjQ1TlEKhrmKwsuuO08V/zYWsqLyuID3pJJShpOC
        MEMdJwOz0XkrkRw2yyxuPfH+aZAXWCGV6blFBMOvCyVq1Caj1NLFKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T19:49:09Z"
  mac: ENC[AES256_GCM,data:h+FqK+vf5AQDbxnmaKt33bArhaV0pbwXZmi4BTHStUzh6LRL8ot1wo7R+U0fPM+6EwV//yNNkZyJaw0TG2oiHsagNSE/WyA4zePa4a2lEDexwak1vAJnYLrTZjKK8qM3KuhMQl9w+/5AOdVdeDvW7F9lRb8gXF2zfIzEHOyeoxo=,iv:4JRAKlqXFfGTTIEojtE0NF2et2axH4MUauyde8JfnCo=,tag:qygHRneMHSqcXB8a2iZtBQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
