# Fill in GHCR_TOKEN before encrypting with: sops -e -i ghcr-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:cpby4u5RDwVnnZyk87Z/MCQCIJxCgU8nRo+kOqLDuBXLoD3DVwOe4hDubKdlF/8EH493U5GWFKeDrFn7nS5bmAgKztkGhm3AJNoqzU7QRDMTfEHyyOGCz+rG00ypFXIY9rmvhk59,iv:rsqkSQxa12sI+wPgzRwZ7oYt3DzZmnqsV7ud29t1r/o=,tag:qFDn+SqHedRI1OfadUnaCQ==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T3JYT3ZGNTdlMUVEaE43
        SDQ3cG1mUm5vVkN3VHpFVHdjUkpRbEpzMGxnCkh4OW96REpKLzRnN2ZKWkY5WHl5
        VFhROS94MVE4QmFCQStVN04wbmkwU00KLS0tIFJJQXpicmFBY2F5bGtEZlBXZG9z
        VTQ1NTY0cjM1VTlWc3BBSW5lOUNvdm8KGniRX3cHiWVUU9lvpOsGCBSPWnOr+IEX
        2AYU67ddaQ9IOn1o/CfDQl3olfwV14MGO+HtbWXLfOb8u+fbUiEV1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T16:33:07Z"
  mac: ENC[AES256_GCM,data:SwD6EMJ/pMKjBdo1yBG8d/aXrhMQllPUyomTex++Xv9dJBw8Jws/4+rszpgdA13+F2Me+FHMIKHjyffx9YJhVUmUw1Y5qLu76nr7MUHKoHu41AC7AkiQ4E9A8uQjEX3Kam9Ue//XbBjbEhWlVS2lMdFVkGHjXqFCEiVwsXN75ss=,iv:zZQg0uNLe5HohjqEAh5HW/GFtKLFc9ZQN0BeURVp0UI=,tag:C202WcU5yrl0OFe7phtqEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
