---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw
spec:
  chartRef:
    kind: OCIRepository
    name: excalidraw
  interval: 1h
  values:
    controllers:
      excalidraw:
        containers:
          app:
            image:
              repository: excalidraw/excalidraw
              tag: latest@sha256:72600b725cfbf0c74f090b748f11bdd41ae205fc065ad02080d7b2ec37566079
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
    service:
      app:
        ports:
          http:
            port: 80
    persistence:
      tmp:
        type: emptyDir
      nginx-cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
      nginx-run:
        type: emptyDir
        globalMounts:
          - path: /var/run
    route:
      app:
        hostnames:
          - "excalidraw.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
