apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:1xxsYDnr+hJmjBRxnNmfY0yqUKp9ADd8o8y/bA58GFU=,iv:LQB9m2dAQtYz+mUMBnahfU7KxoZh4OV868lqzrsIWAc=,tag:jymgMzRFzZ8aNSYYXjDJuw==,type:str]
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:EECadc+vTZQ1LGq41Vj2ZH5zn4KkMNg/enIJ4KkosSw=,iv:7tmR39+0x9Ms9vua9pHVUCgkGB2dEo7FeXUthri3Zvo=,tag:E/Gu6VVsTMMvQ+RJ43minQ==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:IEUM0k5Lol5gU8uCFl2/qjF7+23g0RuWntOJvb/kEI0=,iv:VNBDnw0ChP4Wblip5OPxQuLysHIEnuZ8rTSkFf4zhJI=,tag:O6KjNGDDyYMIR9uTHYupxQ==,type:str]
  HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:P6bL5RRcfNkfKC0QpCin8lV3OHbNfJRw2vDYEbC8AcM=,iv:22ygImCGSoX5SrRDIcd48PvtGLkIUg+klL0Rs6znsVE=,tag:PQE2cpgTT50S0FVGO2X83Q==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWkhHcm1ranltR1pLVHpQ
        bDl3K0ZTL2tKVHNtWVBrTGx5UDRvRWlrSEF3Cm1CZU1UMzkvS2JDUm5NQWJJZ0g3
        UG1zM1E2M001dkFzV1l3c01DenRYSzAKLS0tIEx4WWRLajZtZWlkbmFXaXF3eUxB
        dW1FQnBlMUFMT1hWalVMVGJuMGsvZDQKKZ3ulPrbdwI5vbq2dd9BV/pgdUObCbn5
        jg9LVsh1L5MAmlpnAi7jVIfsf2OdJfOapIQZqtbOL+Rth3SI48H19w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T22:23:20Z"
  mac: ENC[AES256_GCM,data:n4dGo9gt4Ss1ibASKxe79Aspjj/jGEgQZzzO4TGAxOMu0VUQ749afquiBHjlGtxoeeaunRK4pvyaGRsPuX9crWahX1B6MG3NnAjrqe7MzyhDtc9CnMUMOcnpIgORmEmxZ6MG1I+bETPrN9cGg/D96EXJg7hbYLsfLhdv3n847VU=,iv:POnJYZMAIBaMRuBV5niHMbeSAOi4yRG/Rlqo5wyP2Kc=,tag:HSkRZH9q1XPuJQhicLTUIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
