---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "true"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: "https://grafana.${SECRET_DOMAIN}"
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-secret
                      key: GF_SECURITY_ADMIN_PASSWORD
                - name: GF_RENDERING_SERVER_URL
                  value: http://localhost:8081/render
                - name: GF_RENDERING_CALLBACK_URL
                  value: http://localhost:3000/
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
            - name: image-renderer
              image: docker.io/grafana/grafana-image-renderer:v5.7.3
              ports:
                - containerPort: 8081
                  name: renderer
                  protocol: TCP
              env:
                - name: ENABLE_METRICS
                  value: "true"
                - name: HTTP_PORT
                  value: "8081"
              securityContext:
                runAsUser: 65532
                runAsGroup: 65532
                allowPrivilegeEscalation: false
                capabilities: {drop: ["ALL"]}
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 512Mi
              volumeMounts:
                - name: renderer-shm
                  mountPath: /dev/shm
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
            - name: renderer-shm
              emptyDir:
                medium: Memory
                sizeLimit: 256Mi
  httpRoute:
    spec:
      hostnames:
        - "grafana.${SECRET_DOMAIN}"
      parentRefs:
        - name: envoy-internal
          namespace: network
      rules:
        - backendRefs:
            - name: grafana-service
              port: 3000
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
  disableDefaultSecurityContext: All
