# Fill in the values, then encrypt with: sops -e -i secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:vm5rOg3ef/xGw7mawKz9,iv:XfbgEUNCD/C1jZbrS5tG7A0oK+BrssXaCVHnUtv0Sek=,tag:2FyIxdq4AF3g8+Eb5votvA==,type:str]
sops:
  age:
    - recipient: age1s8wkpdcvl3zm8xlz80p8e86qzd2tdmrc69gjgcv8zqc3uwnf6pysaetpqr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVERsN0I4ejRreDgvQ1Jo
        cis3dFVHazBYVTVHWlZnZGJ0Z3loMSsyVVdNClRJMmJHVzdHd3NjcE9mc0tqQ2JF
        TzdqbzlQZXZOWTF0Yzh4N0FraXNOUFUKLS0tIEhzME5FZUR3ZlNHQmZiNUNSb21l
        MStkdmVETkUxK0ttZGwzQUVzQUF1UWMKpaCXyJoM6PI5fd1jQO1zehd+Zy4rDwPX
        iL3GTIfK44Btoy57VdX/+p1LVpmxGXtCW7tYVX8vMDBZ4qrssdeLEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T19:41:52Z"
  mac: ENC[AES256_GCM,data:JQTj7CEriqbvGBnlmrQiJyEq1XRykaiDCZr3lqyj4gmGPHikjrFpqSa12KARlUeAwrJcWouwK5WLb51nxpy+AYnh6XgPdc7SSIA77prgE9zk3nWA2clvv2tPH7B9P4rH4vSH0hYZiRGWtbKTP8QklX12lRug3gkR7hfer9u4uFY=,iv:UfVASHG9ng95Fl/hd44lsyzBbBzWOeXJeN147hr1lpQ=,tag:xOajm+URB4c+q6nIsEpBBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
