---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chartRef:
    kind: OCIRepository
    name: gatus
  interval: 1h
  values:
    controllers:
      gatus:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          gatus-sidecar:
            image:
              repository: ghcr.io/home-operations/gatus-sidecar
              tag: 0.0.13
            args:
              - --auto-httproute
              - --enable-httproute
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            restartPolicy: Always
        containers:
          app:
            image:
              repository: ghcr.io/twin/gatus
              tag: v5.35.0
            env:
              GATUS_DELAY_START_SECONDS: 5
              GATUS_CONFIG_PATH: /config
              GATUS_WEB_PORT: &port 8080
              TZ: Europe/Copenhagen
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    serviceAccount:
      gatus:
        enabled: true
    rbac:
      roles:
        gatus:
          type: ClusterRole
          rules:
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["get", "list", "watch"]
            - apiGroups: ["gateway.networking.k8s.io"]
              resources: ["gateways", "httproutes"]
              verbs: ["get", "list", "watch"]
      bindings:
        gatus:
          type: ClusterRoleBinding
          roleRef:
            identifier: gatus
          subjects:
            - identifier: gatus
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
    persistence:
      data:
        existingClaim: gatus
        globalMounts:
          - path: /data
      config:
        type: emptyDir
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: gatus
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
    configMaps:
      config:
        data:
          config.yaml: |
            storage:
              type: sqlite
              caching: true
              path: /data/gatus.db
            metrics: true
            alerting:
              ntfy:
                url: http://ntfy.monitoring.svc.cluster.local
                topic: gatus
                default-alert:
                  enabled: true
                  send-on-resolved: true
                  failure-threshold: 3
                  success-threshold: 3
            connectivity:
              checker:
                target: 1.1.1.1:53
                interval: 1m
            endpoints:
              - name: Cloudflare
                group: connectivity
                url: "icmp://1.1.1.1"
                interval: 1m
                conditions:
                  - "[CONNECTED] == true"
              - name: Google
                group: connectivity
                url: "icmp://8.8.8.8"
                interval: 1m
                conditions:
                  - "[CONNECTED] == true"
            ui:
              title: Status | Home Ops
              header: Status
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames:
          - "status.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
